// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/distributed_pb.proto

package drillbit.protobuf;

public final class DistributedPb {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_drillbit_protobuf_Descriptors_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_drillbit_protobuf_Descriptors_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_drillbit_protobuf_Descriptors_Descriptor_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_drillbit_protobuf_Descriptors_Descriptor_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_drillbit_protobuf_Slaves_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_drillbit_protobuf_Slaves_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\032proto/distributed_pb.proto\022\021drillbit.p" +
                        "rotobuf\"\203\001\n\013Descriptors\022=\n\ndescriptor\030\001 " +
                        "\003(\0132).drillbit.protobuf.Descriptors.Desc" +
                        "riptor\0325\n\nDescriptor\022\n\n\002id\030\001 \001(\003\022\014\n\004file" +
                        "\030\002 \001(\t\022\r\n\005count\030\003 \001(\003\"\024\n\006Slaves\022\n\n\002id\030\001 " +
                        "\003(\003b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_drillbit_protobuf_Descriptors_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_drillbit_protobuf_Descriptors_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_drillbit_protobuf_Descriptors_descriptor,
                new java.lang.String[]{"Descriptor",});
        internal_static_drillbit_protobuf_Descriptors_Descriptor_descriptor =
                internal_static_drillbit_protobuf_Descriptors_descriptor.getNestedTypes().get(0);
        internal_static_drillbit_protobuf_Descriptors_Descriptor_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_drillbit_protobuf_Descriptors_Descriptor_descriptor,
                new java.lang.String[]{"Id", "File", "Count",});
        internal_static_drillbit_protobuf_Slaves_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_drillbit_protobuf_Slaves_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_drillbit_protobuf_Slaves_descriptor,
                new java.lang.String[]{"Id",});
    }
    private DistributedPb() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    public interface DescriptorsOrBuilder extends
            // @@protoc_insertion_point(interface_extends:drillbit.protobuf.Descriptors)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
         */
        java.util.List<drillbit.protobuf.DistributedPb.Descriptors.Descriptor>
        getDescriptorList();

        /**
         * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
         */
        drillbit.protobuf.DistributedPb.Descriptors.Descriptor getDescriptor(int index);

        /**
         * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
         */
        int getDescriptorCount();

        /**
         * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
         */
        java.util.List<? extends drillbit.protobuf.DistributedPb.Descriptors.DescriptorOrBuilder>
        getDescriptorOrBuilderList();

        /**
         * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
         */
        drillbit.protobuf.DistributedPb.Descriptors.DescriptorOrBuilder getDescriptorOrBuilder(
                int index);
    }

    public interface SlavesOrBuilder extends
            // @@protoc_insertion_point(interface_extends:drillbit.protobuf.Slaves)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated int64 id = 1;</code>
         *
         * @return A list containing the id.
         */
        java.util.List<java.lang.Long> getIdList();

        /**
         * <code>repeated int64 id = 1;</code>
         *
         * @return The count of id.
         */
        int getIdCount();

        /**
         * <code>repeated int64 id = 1;</code>
         *
         * @param index The index of the element to return.
         * @return The id at the given index.
         */
        long getId(int index);
    }

    /**
     * Protobuf type {@code drillbit.protobuf.Descriptors}
     */
    public static final class Descriptors extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:drillbit.protobuf.Descriptors)
            DescriptorsOrBuilder {
        public static final int DESCRIPTOR_FIELD_NUMBER = 1;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:drillbit.protobuf.Descriptors)
        private static final drillbit.protobuf.DistributedPb.Descriptors DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Descriptors>
                PARSER = new com.google.protobuf.AbstractParser<Descriptors>() {
            @java.lang.Override
            public Descriptors parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Descriptors(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new drillbit.protobuf.DistributedPb.Descriptors();
        }

        private java.util.List<drillbit.protobuf.DistributedPb.Descriptors.Descriptor> descriptor_;
        private byte memoizedIsInitialized = -1;

        // Use Descriptors.newBuilder() to construct.
        private Descriptors(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Descriptors() {
            descriptor_ = java.util.Collections.emptyList();
        }

        private Descriptors(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                descriptor_ = new java.util.ArrayList<drillbit.protobuf.DistributedPb.Descriptors.Descriptor>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            descriptor_.add(
                                    input.readMessage(drillbit.protobuf.DistributedPb.Descriptors.Descriptor.parser(), extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    descriptor_ = java.util.Collections.unmodifiableList(descriptor_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Descriptors_descriptor;
        }

        public static drillbit.protobuf.DistributedPb.Descriptors parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static drillbit.protobuf.DistributedPb.Descriptors parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static drillbit.protobuf.DistributedPb.Descriptors parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static drillbit.protobuf.DistributedPb.Descriptors parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static drillbit.protobuf.DistributedPb.Descriptors parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static drillbit.protobuf.DistributedPb.Descriptors parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static drillbit.protobuf.DistributedPb.Descriptors parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static drillbit.protobuf.DistributedPb.Descriptors parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static drillbit.protobuf.DistributedPb.Descriptors parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static drillbit.protobuf.DistributedPb.Descriptors parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static drillbit.protobuf.DistributedPb.Descriptors parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static drillbit.protobuf.DistributedPb.Descriptors parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(drillbit.protobuf.DistributedPb.Descriptors prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static drillbit.protobuf.DistributedPb.Descriptors getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Descriptors> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Descriptors();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Descriptors_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            drillbit.protobuf.DistributedPb.Descriptors.class, drillbit.protobuf.DistributedPb.Descriptors.Builder.class);
        }

        /**
         * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
         */
        @java.lang.Override
        public java.util.List<drillbit.protobuf.DistributedPb.Descriptors.Descriptor> getDescriptorList() {
            return descriptor_;
        }

        /**
         * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
         */
        @java.lang.Override
        public java.util.List<? extends drillbit.protobuf.DistributedPb.Descriptors.DescriptorOrBuilder>
        getDescriptorOrBuilderList() {
            return descriptor_;
        }

        /**
         * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
         */
        @java.lang.Override
        public int getDescriptorCount() {
            return descriptor_.size();
        }

        /**
         * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
         */
        @java.lang.Override
        public drillbit.protobuf.DistributedPb.Descriptors.Descriptor getDescriptor(int index) {
            return descriptor_.get(index);
        }

        /**
         * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
         */
        @java.lang.Override
        public drillbit.protobuf.DistributedPb.Descriptors.DescriptorOrBuilder getDescriptorOrBuilder(
                int index) {
            return descriptor_.get(index);
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < descriptor_.size(); i++) {
                output.writeMessage(1, descriptor_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < descriptor_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, descriptor_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof drillbit.protobuf.DistributedPb.Descriptors)) {
                return super.equals(obj);
            }
            drillbit.protobuf.DistributedPb.Descriptors other = (drillbit.protobuf.DistributedPb.Descriptors) obj;

            if (!getDescriptorList()
                    .equals(other.getDescriptorList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getDescriptorCount() > 0) {
                hash = (37 * hash) + DESCRIPTOR_FIELD_NUMBER;
                hash = (53 * hash) + getDescriptorList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Descriptors> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public drillbit.protobuf.DistributedPb.Descriptors getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        public interface DescriptorOrBuilder extends
                // @@protoc_insertion_point(interface_extends:drillbit.protobuf.Descriptors.Descriptor)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>int64 id = 1;</code>
             *
             * @return The id.
             */
            long getId();

            /**
             * <code>string file = 2;</code>
             *
             * @return The file.
             */
            java.lang.String getFile();

            /**
             * <code>string file = 2;</code>
             *
             * @return The bytes for file.
             */
            com.google.protobuf.ByteString
            getFileBytes();

            /**
             * <code>int64 count = 3;</code>
             *
             * @return The count.
             */
            long getCount();
        }

        /**
         * Protobuf type {@code drillbit.protobuf.Descriptors.Descriptor}
         */
        public static final class Descriptor extends
                com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:drillbit.protobuf.Descriptors.Descriptor)
                DescriptorOrBuilder {
            public static final int ID_FIELD_NUMBER = 1;
            public static final int FILE_FIELD_NUMBER = 2;
            public static final int COUNT_FIELD_NUMBER = 3;
            private static final long serialVersionUID = 0L;
            // @@protoc_insertion_point(class_scope:drillbit.protobuf.Descriptors.Descriptor)
            private static final drillbit.protobuf.DistributedPb.Descriptors.Descriptor DEFAULT_INSTANCE;
            private static final com.google.protobuf.Parser<Descriptor>
                    PARSER = new com.google.protobuf.AbstractParser<Descriptor>() {
                @java.lang.Override
                public Descriptor parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new Descriptor(input, extensionRegistry);
                }
            };

            static {
                DEFAULT_INSTANCE = new drillbit.protobuf.DistributedPb.Descriptors.Descriptor();
            }

            private long id_;
            private volatile java.lang.Object file_;
            private long count_;
            private byte memoizedIsInitialized = -1;

            // Use Descriptor.newBuilder() to construct.
            private Descriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
                super(builder);
            }
            private Descriptor() {
                file_ = "";
            }

            private Descriptor(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                this();
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {

                                id_ = input.readInt64();
                                break;
                            }
                            case 18: {
                                java.lang.String s = input.readStringRequireUtf8();

                                file_ = s;
                                break;
                            }
                            case 24: {

                                count_ = input.readInt64();
                                break;
                            }
                            default: {
                                if (!parseUnknownField(
                                        input, unknownFields, extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e).setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Descriptors_Descriptor_descriptor;
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor parseFrom(
                    java.nio.ByteBuffer data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor parseFrom(
                    java.nio.ByteBuffer data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input);
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            public static Builder newBuilder() {
                return DEFAULT_INSTANCE.toBuilder();
            }

            public static Builder newBuilder(drillbit.protobuf.DistributedPb.Descriptors.Descriptor prototype) {
                return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
            }

            public static drillbit.protobuf.DistributedPb.Descriptors.Descriptor getDefaultInstance() {
                return DEFAULT_INSTANCE;
            }

            public static com.google.protobuf.Parser<Descriptor> parser() {
                return PARSER;
            }

            @java.lang.Override
            @SuppressWarnings({"unused"})
            protected java.lang.Object newInstance(
                    UnusedPrivateParameter unused) {
                return new Descriptor();
            }

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
                return this.unknownFields;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Descriptors_Descriptor_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                drillbit.protobuf.DistributedPb.Descriptors.Descriptor.class, drillbit.protobuf.DistributedPb.Descriptors.Descriptor.Builder.class);
            }

            /**
             * <code>int64 id = 1;</code>
             *
             * @return The id.
             */
            @java.lang.Override
            public long getId() {
                return id_;
            }

            /**
             * <code>string file = 2;</code>
             *
             * @return The file.
             */
            @java.lang.Override
            public java.lang.String getFile() {
                java.lang.Object ref = file_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    file_ = s;
                    return s;
                }
            }

            /**
             * <code>string file = 2;</code>
             *
             * @return The bytes for file.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getFileBytes() {
                java.lang.Object ref = file_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    file_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>int64 count = 3;</code>
             *
             * @return The count.
             */
            @java.lang.Override
            public long getCount() {
                return count_;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) return true;
                if (isInitialized == 0) return false;

                memoizedIsInitialized = 1;
                return true;
            }

            @java.lang.Override
            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                if (id_ != 0L) {
                    output.writeInt64(1, id_);
                }
                if (!getFileBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 2, file_);
                }
                if (count_ != 0L) {
                    output.writeInt64(3, count_);
                }
                unknownFields.writeTo(output);
            }

            @java.lang.Override
            public int getSerializedSize() {
                int size = memoizedSize;
                if (size != -1) return size;

                size = 0;
                if (id_ != 0L) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt64Size(1, id_);
                }
                if (!getFileBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, file_);
                }
                if (count_ != 0L) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt64Size(3, count_);
                }
                size += unknownFields.getSerializedSize();
                memoizedSize = size;
                return size;
            }

            @java.lang.Override
            public boolean equals(final java.lang.Object obj) {
                if (obj == this) {
                    return true;
                }
                if (!(obj instanceof drillbit.protobuf.DistributedPb.Descriptors.Descriptor)) {
                    return super.equals(obj);
                }
                drillbit.protobuf.DistributedPb.Descriptors.Descriptor other = (drillbit.protobuf.DistributedPb.Descriptors.Descriptor) obj;

                if (getId()
                        != other.getId()) return false;
                if (!getFile()
                        .equals(other.getFile())) return false;
                if (getCount()
                        != other.getCount()) return false;
                if (!unknownFields.equals(other.unknownFields)) return false;
                return true;
            }

            @java.lang.Override
            public int hashCode() {
                if (memoizedHashCode != 0) {
                    return memoizedHashCode;
                }
                int hash = 41;
                hash = (19 * hash) + getDescriptor().hashCode();
                hash = (37 * hash) + ID_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getId());
                hash = (37 * hash) + FILE_FIELD_NUMBER;
                hash = (53 * hash) + getFile().hashCode();
                hash = (37 * hash) + COUNT_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getCount());
                hash = (29 * hash) + unknownFields.hashCode();
                memoizedHashCode = hash;
                return hash;
            }

            @java.lang.Override
            public Builder newBuilderForType() {
                return newBuilder();
            }

            @java.lang.Override
            public Builder toBuilder() {
                return this == DEFAULT_INSTANCE
                        ? new Builder() : new Builder().mergeFrom(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            @java.lang.Override
            public com.google.protobuf.Parser<Descriptor> getParserForType() {
                return PARSER;
            }

            @java.lang.Override
            public drillbit.protobuf.DistributedPb.Descriptors.Descriptor getDefaultInstanceForType() {
                return DEFAULT_INSTANCE;
            }

            /**
             * Protobuf type {@code drillbit.protobuf.Descriptors.Descriptor}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:drillbit.protobuf.Descriptors.Descriptor)
                    drillbit.protobuf.DistributedPb.Descriptors.DescriptorOrBuilder {
                private long id_;
                private java.lang.Object file_ = "";
                private long count_;

                // Construct using drillbit.protobuf.DistributedPb.Descriptors.Descriptor.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Descriptors_Descriptor_descriptor;
                }

                @java.lang.Override
                protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Descriptors_Descriptor_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    drillbit.protobuf.DistributedPb.Descriptors.Descriptor.class, drillbit.protobuf.DistributedPb.Descriptors.Descriptor.Builder.class);
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessageV3
                            .alwaysUseFieldBuilders) {
                    }
                }

                @java.lang.Override
                public Builder clear() {
                    super.clear();
                    id_ = 0L;

                    file_ = "";

                    count_ = 0L;

                    return this;
                }

                @java.lang.Override
                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Descriptors_Descriptor_descriptor;
                }

                @java.lang.Override
                public drillbit.protobuf.DistributedPb.Descriptors.Descriptor getDefaultInstanceForType() {
                    return drillbit.protobuf.DistributedPb.Descriptors.Descriptor.getDefaultInstance();
                }

                @java.lang.Override
                public drillbit.protobuf.DistributedPb.Descriptors.Descriptor build() {
                    drillbit.protobuf.DistributedPb.Descriptors.Descriptor result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                @java.lang.Override
                public drillbit.protobuf.DistributedPb.Descriptors.Descriptor buildPartial() {
                    drillbit.protobuf.DistributedPb.Descriptors.Descriptor result = new drillbit.protobuf.DistributedPb.Descriptors.Descriptor(this);
                    result.id_ = id_;
                    result.file_ = file_;
                    result.count_ = count_;
                    onBuilt();
                    return result;
                }

                @java.lang.Override
                public Builder clone() {
                    return super.clone();
                }

                @java.lang.Override
                public Builder setField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.setField(field, value);
                }

                @java.lang.Override
                public Builder clearField(
                        com.google.protobuf.Descriptors.FieldDescriptor field) {
                    return super.clearField(field);
                }

                @java.lang.Override
                public Builder clearOneof(
                        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                    return super.clearOneof(oneof);
                }

                @java.lang.Override
                public Builder setRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        int index, java.lang.Object value) {
                    return super.setRepeatedField(field, index, value);
                }

                @java.lang.Override
                public Builder addRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.addRepeatedField(field, value);
                }

                @java.lang.Override
                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof drillbit.protobuf.DistributedPb.Descriptors.Descriptor) {
                        return mergeFrom((drillbit.protobuf.DistributedPb.Descriptors.Descriptor) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(drillbit.protobuf.DistributedPb.Descriptors.Descriptor other) {
                    if (other == drillbit.protobuf.DistributedPb.Descriptors.Descriptor.getDefaultInstance())
                        return this;
                    if (other.getId() != 0L) {
                        setId(other.getId());
                    }
                    if (!other.getFile().isEmpty()) {
                        file_ = other.file_;
                        onChanged();
                    }
                    if (other.getCount() != 0L) {
                        setCount(other.getCount());
                    }
                    this.mergeUnknownFields(other.unknownFields);
                    onChanged();
                    return this;
                }

                @java.lang.Override
                public final boolean isInitialized() {
                    return true;
                }

                @java.lang.Override
                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    drillbit.protobuf.DistributedPb.Descriptors.Descriptor parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (drillbit.protobuf.DistributedPb.Descriptors.Descriptor) e.getUnfinishedMessage();
                        throw e.unwrapIOException();
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                /**
                 * <code>int64 id = 1;</code>
                 *
                 * @return The id.
                 */
                @java.lang.Override
                public long getId() {
                    return id_;
                }

                /**
                 * <code>int64 id = 1;</code>
                 *
                 * @param value The id to set.
                 * @return This builder for chaining.
                 */
                public Builder setId(long value) {

                    id_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>int64 id = 1;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearId() {

                    id_ = 0L;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string file = 2;</code>
                 *
                 * @return The file.
                 */
                public java.lang.String getFile() {
                    java.lang.Object ref = file_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        file_ = s;
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }

                /**
                 * <code>string file = 2;</code>
                 *
                 * @param value The file to set.
                 * @return This builder for chaining.
                 */
                public Builder setFile(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    file_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string file = 2;</code>
                 *
                 * @return The bytes for file.
                 */
                public com.google.protobuf.ByteString
                getFileBytes() {
                    java.lang.Object ref = file_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        file_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>string file = 2;</code>
                 *
                 * @param value The bytes for file to set.
                 * @return This builder for chaining.
                 */
                public Builder setFileBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    file_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string file = 2;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearFile() {

                    file_ = getDefaultInstance().getFile();
                    onChanged();
                    return this;
                }

                /**
                 * <code>int64 count = 3;</code>
                 *
                 * @return The count.
                 */
                @java.lang.Override
                public long getCount() {
                    return count_;
                }

                /**
                 * <code>int64 count = 3;</code>
                 *
                 * @param value The count to set.
                 * @return This builder for chaining.
                 */
                public Builder setCount(long value) {

                    count_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>int64 count = 3;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearCount() {

                    count_ = 0L;
                    onChanged();
                    return this;
                }

                @java.lang.Override
                public final Builder setUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.setUnknownFields(unknownFields);
                }

                @java.lang.Override
                public final Builder mergeUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.mergeUnknownFields(unknownFields);
                }


                // @@protoc_insertion_point(builder_scope:drillbit.protobuf.Descriptors.Descriptor)
            }

        }

        /**
         * Protobuf type {@code drillbit.protobuf.Descriptors}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:drillbit.protobuf.Descriptors)
                drillbit.protobuf.DistributedPb.DescriptorsOrBuilder {
            private int bitField0_;
            private java.util.List<drillbit.protobuf.DistributedPb.Descriptors.Descriptor> descriptor_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    drillbit.protobuf.DistributedPb.Descriptors.Descriptor, drillbit.protobuf.DistributedPb.Descriptors.Descriptor.Builder, drillbit.protobuf.DistributedPb.Descriptors.DescriptorOrBuilder> descriptorBuilder_;

            // Construct using drillbit.protobuf.DistributedPb.Descriptors.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Descriptors_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Descriptors_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                drillbit.protobuf.DistributedPb.Descriptors.class, drillbit.protobuf.DistributedPb.Descriptors.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getDescriptorFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (descriptorBuilder_ == null) {
                    descriptor_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    descriptorBuilder_.clear();
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Descriptors_descriptor;
            }

            @java.lang.Override
            public drillbit.protobuf.DistributedPb.Descriptors getDefaultInstanceForType() {
                return drillbit.protobuf.DistributedPb.Descriptors.getDefaultInstance();
            }

            @java.lang.Override
            public drillbit.protobuf.DistributedPb.Descriptors build() {
                drillbit.protobuf.DistributedPb.Descriptors result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public drillbit.protobuf.DistributedPb.Descriptors buildPartial() {
                drillbit.protobuf.DistributedPb.Descriptors result = new drillbit.protobuf.DistributedPb.Descriptors(this);
                int from_bitField0_ = bitField0_;
                if (descriptorBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)) {
                        descriptor_ = java.util.Collections.unmodifiableList(descriptor_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.descriptor_ = descriptor_;
                } else {
                    result.descriptor_ = descriptorBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof drillbit.protobuf.DistributedPb.Descriptors) {
                    return mergeFrom((drillbit.protobuf.DistributedPb.Descriptors) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(drillbit.protobuf.DistributedPb.Descriptors other) {
                if (other == drillbit.protobuf.DistributedPb.Descriptors.getDefaultInstance()) return this;
                if (descriptorBuilder_ == null) {
                    if (!other.descriptor_.isEmpty()) {
                        if (descriptor_.isEmpty()) {
                            descriptor_ = other.descriptor_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureDescriptorIsMutable();
                            descriptor_.addAll(other.descriptor_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.descriptor_.isEmpty()) {
                        if (descriptorBuilder_.isEmpty()) {
                            descriptorBuilder_.dispose();
                            descriptorBuilder_ = null;
                            descriptor_ = other.descriptor_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            descriptorBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getDescriptorFieldBuilder() : null;
                        } else {
                            descriptorBuilder_.addAllMessages(other.descriptor_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                drillbit.protobuf.DistributedPb.Descriptors parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (drillbit.protobuf.DistributedPb.Descriptors) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private void ensureDescriptorIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    descriptor_ = new java.util.ArrayList<drillbit.protobuf.DistributedPb.Descriptors.Descriptor>(descriptor_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public java.util.List<drillbit.protobuf.DistributedPb.Descriptors.Descriptor> getDescriptorList() {
                if (descriptorBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(descriptor_);
                } else {
                    return descriptorBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public int getDescriptorCount() {
                if (descriptorBuilder_ == null) {
                    return descriptor_.size();
                } else {
                    return descriptorBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public drillbit.protobuf.DistributedPb.Descriptors.Descriptor getDescriptor(int index) {
                if (descriptorBuilder_ == null) {
                    return descriptor_.get(index);
                } else {
                    return descriptorBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public Builder setDescriptor(
                    int index, drillbit.protobuf.DistributedPb.Descriptors.Descriptor value) {
                if (descriptorBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDescriptorIsMutable();
                    descriptor_.set(index, value);
                    onChanged();
                } else {
                    descriptorBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public Builder setDescriptor(
                    int index, drillbit.protobuf.DistributedPb.Descriptors.Descriptor.Builder builderForValue) {
                if (descriptorBuilder_ == null) {
                    ensureDescriptorIsMutable();
                    descriptor_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    descriptorBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public Builder addDescriptor(drillbit.protobuf.DistributedPb.Descriptors.Descriptor value) {
                if (descriptorBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDescriptorIsMutable();
                    descriptor_.add(value);
                    onChanged();
                } else {
                    descriptorBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public Builder addDescriptor(
                    int index, drillbit.protobuf.DistributedPb.Descriptors.Descriptor value) {
                if (descriptorBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDescriptorIsMutable();
                    descriptor_.add(index, value);
                    onChanged();
                } else {
                    descriptorBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public Builder addDescriptor(
                    drillbit.protobuf.DistributedPb.Descriptors.Descriptor.Builder builderForValue) {
                if (descriptorBuilder_ == null) {
                    ensureDescriptorIsMutable();
                    descriptor_.add(builderForValue.build());
                    onChanged();
                } else {
                    descriptorBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public Builder addDescriptor(
                    int index, drillbit.protobuf.DistributedPb.Descriptors.Descriptor.Builder builderForValue) {
                if (descriptorBuilder_ == null) {
                    ensureDescriptorIsMutable();
                    descriptor_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    descriptorBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public Builder addAllDescriptor(
                    java.lang.Iterable<? extends drillbit.protobuf.DistributedPb.Descriptors.Descriptor> values) {
                if (descriptorBuilder_ == null) {
                    ensureDescriptorIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, descriptor_);
                    onChanged();
                } else {
                    descriptorBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public Builder clearDescriptor() {
                if (descriptorBuilder_ == null) {
                    descriptor_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    descriptorBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public Builder removeDescriptor(int index) {
                if (descriptorBuilder_ == null) {
                    ensureDescriptorIsMutable();
                    descriptor_.remove(index);
                    onChanged();
                } else {
                    descriptorBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public drillbit.protobuf.DistributedPb.Descriptors.Descriptor.Builder getDescriptorBuilder(
                    int index) {
                return getDescriptorFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public drillbit.protobuf.DistributedPb.Descriptors.DescriptorOrBuilder getDescriptorOrBuilder(
                    int index) {
                if (descriptorBuilder_ == null) {
                    return descriptor_.get(index);
                } else {
                    return descriptorBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public java.util.List<? extends drillbit.protobuf.DistributedPb.Descriptors.DescriptorOrBuilder>
            getDescriptorOrBuilderList() {
                if (descriptorBuilder_ != null) {
                    return descriptorBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(descriptor_);
                }
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public drillbit.protobuf.DistributedPb.Descriptors.Descriptor.Builder addDescriptorBuilder() {
                return getDescriptorFieldBuilder().addBuilder(
                        drillbit.protobuf.DistributedPb.Descriptors.Descriptor.getDefaultInstance());
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public drillbit.protobuf.DistributedPb.Descriptors.Descriptor.Builder addDescriptorBuilder(
                    int index) {
                return getDescriptorFieldBuilder().addBuilder(
                        index, drillbit.protobuf.DistributedPb.Descriptors.Descriptor.getDefaultInstance());
            }

            /**
             * <code>repeated .drillbit.protobuf.Descriptors.Descriptor descriptor = 1;</code>
             */
            public java.util.List<drillbit.protobuf.DistributedPb.Descriptors.Descriptor.Builder>
            getDescriptorBuilderList() {
                return getDescriptorFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    drillbit.protobuf.DistributedPb.Descriptors.Descriptor, drillbit.protobuf.DistributedPb.Descriptors.Descriptor.Builder, drillbit.protobuf.DistributedPb.Descriptors.DescriptorOrBuilder>
            getDescriptorFieldBuilder() {
                if (descriptorBuilder_ == null) {
                    descriptorBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            drillbit.protobuf.DistributedPb.Descriptors.Descriptor, drillbit.protobuf.DistributedPb.Descriptors.Descriptor.Builder, drillbit.protobuf.DistributedPb.Descriptors.DescriptorOrBuilder>(
                            descriptor_,
                            ((bitField0_ & 0x00000001) != 0),
                            getParentForChildren(),
                            isClean());
                    descriptor_ = null;
                }
                return descriptorBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:drillbit.protobuf.Descriptors)
        }

    }

    /**
     * Protobuf type {@code drillbit.protobuf.Slaves}
     */
    public static final class Slaves extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:drillbit.protobuf.Slaves)
            SlavesOrBuilder {
        public static final int ID_FIELD_NUMBER = 1;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:drillbit.protobuf.Slaves)
        private static final drillbit.protobuf.DistributedPb.Slaves DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Slaves>
                PARSER = new com.google.protobuf.AbstractParser<Slaves>() {
            @java.lang.Override
            public Slaves parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Slaves(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new drillbit.protobuf.DistributedPb.Slaves();
        }

        private com.google.protobuf.Internal.LongList id_;
        private int idMemoizedSerializedSize = -1;
        private byte memoizedIsInitialized = -1;

        // Use Slaves.newBuilder() to construct.
        private Slaves(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Slaves() {
            id_ = emptyLongList();
        }

        private Slaves(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                id_ = newLongList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            id_.addLong(input.readInt64());
                            break;
                        }
                        case 10: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                                id_ = newLongList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                id_.addLong(input.readInt64());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    id_.makeImmutable(); // C
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Slaves_descriptor;
        }

        public static drillbit.protobuf.DistributedPb.Slaves parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static drillbit.protobuf.DistributedPb.Slaves parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static drillbit.protobuf.DistributedPb.Slaves parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static drillbit.protobuf.DistributedPb.Slaves parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static drillbit.protobuf.DistributedPb.Slaves parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static drillbit.protobuf.DistributedPb.Slaves parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static drillbit.protobuf.DistributedPb.Slaves parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static drillbit.protobuf.DistributedPb.Slaves parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static drillbit.protobuf.DistributedPb.Slaves parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static drillbit.protobuf.DistributedPb.Slaves parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static drillbit.protobuf.DistributedPb.Slaves parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static drillbit.protobuf.DistributedPb.Slaves parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(drillbit.protobuf.DistributedPb.Slaves prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static drillbit.protobuf.DistributedPb.Slaves getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Slaves> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Slaves();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Slaves_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            drillbit.protobuf.DistributedPb.Slaves.class, drillbit.protobuf.DistributedPb.Slaves.Builder.class);
        }

        /**
         * <code>repeated int64 id = 1;</code>
         *
         * @return A list containing the id.
         */
        @java.lang.Override
        public java.util.List<java.lang.Long>
        getIdList() {
            return id_;
        }

        /**
         * <code>repeated int64 id = 1;</code>
         *
         * @return The count of id.
         */
        public int getIdCount() {
            return id_.size();
        }

        /**
         * <code>repeated int64 id = 1;</code>
         *
         * @param index The index of the element to return.
         * @return The id at the given index.
         */
        public long getId(int index) {
            return id_.getLong(index);
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (getIdList().size() > 0) {
                output.writeUInt32NoTag(10);
                output.writeUInt32NoTag(idMemoizedSerializedSize);
            }
            for (int i = 0; i < id_.size(); i++) {
                output.writeInt64NoTag(id_.getLong(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < id_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeInt64SizeNoTag(id_.getLong(i));
                }
                size += dataSize;
                if (!getIdList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(dataSize);
                }
                idMemoizedSerializedSize = dataSize;
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof drillbit.protobuf.DistributedPb.Slaves)) {
                return super.equals(obj);
            }
            drillbit.protobuf.DistributedPb.Slaves other = (drillbit.protobuf.DistributedPb.Slaves) obj;

            if (!getIdList()
                    .equals(other.getIdList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getIdCount() > 0) {
                hash = (37 * hash) + ID_FIELD_NUMBER;
                hash = (53 * hash) + getIdList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Slaves> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public drillbit.protobuf.DistributedPb.Slaves getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code drillbit.protobuf.Slaves}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:drillbit.protobuf.Slaves)
                drillbit.protobuf.DistributedPb.SlavesOrBuilder {
            private int bitField0_;
            private com.google.protobuf.Internal.LongList id_ = emptyLongList();

            // Construct using drillbit.protobuf.DistributedPb.Slaves.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Slaves_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Slaves_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                drillbit.protobuf.DistributedPb.Slaves.class, drillbit.protobuf.DistributedPb.Slaves.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                id_ = emptyLongList();
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return drillbit.protobuf.DistributedPb.internal_static_drillbit_protobuf_Slaves_descriptor;
            }

            @java.lang.Override
            public drillbit.protobuf.DistributedPb.Slaves getDefaultInstanceForType() {
                return drillbit.protobuf.DistributedPb.Slaves.getDefaultInstance();
            }

            @java.lang.Override
            public drillbit.protobuf.DistributedPb.Slaves build() {
                drillbit.protobuf.DistributedPb.Slaves result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public drillbit.protobuf.DistributedPb.Slaves buildPartial() {
                drillbit.protobuf.DistributedPb.Slaves result = new drillbit.protobuf.DistributedPb.Slaves(this);
                int from_bitField0_ = bitField0_;
                if (((bitField0_ & 0x00000001) != 0)) {
                    id_.makeImmutable();
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.id_ = id_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof drillbit.protobuf.DistributedPb.Slaves) {
                    return mergeFrom((drillbit.protobuf.DistributedPb.Slaves) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(drillbit.protobuf.DistributedPb.Slaves other) {
                if (other == drillbit.protobuf.DistributedPb.Slaves.getDefaultInstance()) return this;
                if (!other.id_.isEmpty()) {
                    if (id_.isEmpty()) {
                        id_ = other.id_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureIdIsMutable();
                        id_.addAll(other.id_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                drillbit.protobuf.DistributedPb.Slaves parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (drillbit.protobuf.DistributedPb.Slaves) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private void ensureIdIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    id_ = mutableCopy(id_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated int64 id = 1;</code>
             *
             * @return A list containing the id.
             */
            public java.util.List<java.lang.Long>
            getIdList() {
                return ((bitField0_ & 0x00000001) != 0) ?
                        java.util.Collections.unmodifiableList(id_) : id_;
            }

            /**
             * <code>repeated int64 id = 1;</code>
             *
             * @return The count of id.
             */
            public int getIdCount() {
                return id_.size();
            }

            /**
             * <code>repeated int64 id = 1;</code>
             *
             * @param index The index of the element to return.
             * @return The id at the given index.
             */
            public long getId(int index) {
                return id_.getLong(index);
            }

            /**
             * <code>repeated int64 id = 1;</code>
             *
             * @param index The index to set the value at.
             * @param value The id to set.
             * @return This builder for chaining.
             */
            public Builder setId(
                    int index, long value) {
                ensureIdIsMutable();
                id_.setLong(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int64 id = 1;</code>
             *
             * @param value The id to add.
             * @return This builder for chaining.
             */
            public Builder addId(long value) {
                ensureIdIsMutable();
                id_.addLong(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int64 id = 1;</code>
             *
             * @param values The id to add.
             * @return This builder for chaining.
             */
            public Builder addAllId(
                    java.lang.Iterable<? extends java.lang.Long> values) {
                ensureIdIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, id_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int64 id = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearId() {
                id_ = emptyLongList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:drillbit.protobuf.Slaves)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
