// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network_pb.proto

package drillbit.protobuf;

public final class NetworkPb {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_drillbit_protobuf_NeuralNetwork_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_drillbit_protobuf_NeuralNetwork_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020network_pb.proto\022\021drillbit.protobuf\"P\n" +
                        "\rNeuralNetwork\022\022\n\nregression\030\001 \001(\010\022\r\n\005mo" +
                        "del\030\002 \001(\014\022\014\n\004dims\030\004 \001(\005\022\016\n\006labels\030\003 \003(\tb" +
                        "\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_drillbit_protobuf_NeuralNetwork_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_drillbit_protobuf_NeuralNetwork_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_drillbit_protobuf_NeuralNetwork_descriptor,
                new java.lang.String[]{"Regression", "Model", "Dims", "Labels",});
    }

    private NetworkPb() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface NeuralNetworkOrBuilder extends
            // @@protoc_insertion_point(interface_extends:drillbit.protobuf.NeuralNetwork)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bool regression = 1;</code>
         *
         * @return The regression.
         */
        boolean getRegression();

        /**
         * <code>bytes model = 2;</code>
         *
         * @return The model.
         */
        com.google.protobuf.ByteString getModel();

        /**
         * <code>int32 dims = 4;</code>
         *
         * @return The dims.
         */
        int getDims();

        /**
         * <code>repeated string labels = 3;</code>
         *
         * @return A list containing the labels.
         */
        java.util.List<java.lang.String>
        getLabelsList();

        /**
         * <code>repeated string labels = 3;</code>
         *
         * @return The count of labels.
         */
        int getLabelsCount();

        /**
         * <code>repeated string labels = 3;</code>
         *
         * @param index The index of the element to return.
         * @return The labels at the given index.
         */
        java.lang.String getLabels(int index);

        /**
         * <code>repeated string labels = 3;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the labels at the given index.
         */
        com.google.protobuf.ByteString
        getLabelsBytes(int index);
    }

    /**
     * Protobuf type {@code drillbit.protobuf.NeuralNetwork}
     */
    public static final class NeuralNetwork extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:drillbit.protobuf.NeuralNetwork)
            NeuralNetworkOrBuilder {
        public static final int REGRESSION_FIELD_NUMBER = 1;
        public static final int MODEL_FIELD_NUMBER = 2;
        public static final int DIMS_FIELD_NUMBER = 4;
        public static final int LABELS_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:drillbit.protobuf.NeuralNetwork)
        private static final drillbit.protobuf.NetworkPb.NeuralNetwork DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<NeuralNetwork>
                PARSER = new com.google.protobuf.AbstractParser<NeuralNetwork>() {
            @java.lang.Override
            public NeuralNetwork parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            DEFAULT_INSTANCE = new drillbit.protobuf.NetworkPb.NeuralNetwork();
        }

        private boolean regression_ = false;
        private com.google.protobuf.ByteString model_ = com.google.protobuf.ByteString.EMPTY;
        private int dims_ = 0;
        @SuppressWarnings("serial")
        private com.google.protobuf.LazyStringArrayList labels_ =
                com.google.protobuf.LazyStringArrayList.emptyList();
        private byte memoizedIsInitialized = -1;
        // Use NeuralNetwork.newBuilder() to construct.
        private NeuralNetwork(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private NeuralNetwork() {
            model_ = com.google.protobuf.ByteString.EMPTY;
            labels_ =
                    com.google.protobuf.LazyStringArrayList.emptyList();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return drillbit.protobuf.NetworkPb.internal_static_drillbit_protobuf_NeuralNetwork_descriptor;
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(drillbit.protobuf.NetworkPb.NeuralNetwork prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static drillbit.protobuf.NetworkPb.NeuralNetwork getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<NeuralNetwork> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new NeuralNetwork();
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return drillbit.protobuf.NetworkPb.internal_static_drillbit_protobuf_NeuralNetwork_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            drillbit.protobuf.NetworkPb.NeuralNetwork.class, drillbit.protobuf.NetworkPb.NeuralNetwork.Builder.class);
        }

        /**
         * <code>bool regression = 1;</code>
         *
         * @return The regression.
         */
        @java.lang.Override
        public boolean getRegression() {
            return regression_;
        }

        /**
         * <code>bytes model = 2;</code>
         *
         * @return The model.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getModel() {
            return model_;
        }

        /**
         * <code>int32 dims = 4;</code>
         *
         * @return The dims.
         */
        @java.lang.Override
        public int getDims() {
            return dims_;
        }

        /**
         * <code>repeated string labels = 3;</code>
         *
         * @return A list containing the labels.
         */
        public com.google.protobuf.ProtocolStringList
        getLabelsList() {
            return labels_;
        }

        /**
         * <code>repeated string labels = 3;</code>
         *
         * @return The count of labels.
         */
        public int getLabelsCount() {
            return labels_.size();
        }

        /**
         * <code>repeated string labels = 3;</code>
         *
         * @param index The index of the element to return.
         * @return The labels at the given index.
         */
        public java.lang.String getLabels(int index) {
            return labels_.get(index);
        }

        /**
         * <code>repeated string labels = 3;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the labels at the given index.
         */
        public com.google.protobuf.ByteString
        getLabelsBytes(int index) {
            return labels_.getByteString(index);
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (regression_ != false) {
                output.writeBool(1, regression_);
            }
            if (!model_.isEmpty()) {
                output.writeBytes(2, model_);
            }
            for (int i = 0; i < labels_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, labels_.getRaw(i));
            }
            if (dims_ != 0) {
                output.writeInt32(4, dims_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (regression_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(1, regression_);
            }
            if (!model_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, model_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < labels_.size(); i++) {
                    dataSize += computeStringSizeNoTag(labels_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getLabelsList().size();
            }
            if (dims_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, dims_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof drillbit.protobuf.NetworkPb.NeuralNetwork)) {
                return super.equals(obj);
            }
            drillbit.protobuf.NetworkPb.NeuralNetwork other = (drillbit.protobuf.NetworkPb.NeuralNetwork) obj;

            if (getRegression()
                    != other.getRegression()) return false;
            if (!getModel()
                    .equals(other.getModel())) return false;
            if (getDims()
                    != other.getDims()) return false;
            if (!getLabelsList()
                    .equals(other.getLabelsList())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + REGRESSION_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getRegression());
            hash = (37 * hash) + MODEL_FIELD_NUMBER;
            hash = (53 * hash) + getModel().hashCode();
            hash = (37 * hash) + DIMS_FIELD_NUMBER;
            hash = (53 * hash) + getDims();
            if (getLabelsCount() > 0) {
                hash = (37 * hash) + LABELS_FIELD_NUMBER;
                hash = (53 * hash) + getLabelsList().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<NeuralNetwork> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public drillbit.protobuf.NetworkPb.NeuralNetwork getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code drillbit.protobuf.NeuralNetwork}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:drillbit.protobuf.NeuralNetwork)
                drillbit.protobuf.NetworkPb.NeuralNetworkOrBuilder {
            private int bitField0_;
            private boolean regression_;
            private com.google.protobuf.ByteString model_ = com.google.protobuf.ByteString.EMPTY;
            private int dims_;
            private com.google.protobuf.LazyStringArrayList labels_ =
                    com.google.protobuf.LazyStringArrayList.emptyList();

            // Construct using drillbit.protobuf.NetworkPb.NeuralNetwork.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return drillbit.protobuf.NetworkPb.internal_static_drillbit_protobuf_NeuralNetwork_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return drillbit.protobuf.NetworkPb.internal_static_drillbit_protobuf_NeuralNetwork_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                drillbit.protobuf.NetworkPb.NeuralNetwork.class, drillbit.protobuf.NetworkPb.NeuralNetwork.Builder.class);
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                regression_ = false;
                model_ = com.google.protobuf.ByteString.EMPTY;
                dims_ = 0;
                labels_ =
                        com.google.protobuf.LazyStringArrayList.emptyList();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return drillbit.protobuf.NetworkPb.internal_static_drillbit_protobuf_NeuralNetwork_descriptor;
            }

            @java.lang.Override
            public drillbit.protobuf.NetworkPb.NeuralNetwork getDefaultInstanceForType() {
                return drillbit.protobuf.NetworkPb.NeuralNetwork.getDefaultInstance();
            }

            @java.lang.Override
            public drillbit.protobuf.NetworkPb.NeuralNetwork build() {
                drillbit.protobuf.NetworkPb.NeuralNetwork result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public drillbit.protobuf.NetworkPb.NeuralNetwork buildPartial() {
                drillbit.protobuf.NetworkPb.NeuralNetwork result = new drillbit.protobuf.NetworkPb.NeuralNetwork(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(drillbit.protobuf.NetworkPb.NeuralNetwork result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.regression_ = regression_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.model_ = model_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.dims_ = dims_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    labels_.makeImmutable();
                    result.labels_ = labels_;
                }
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof drillbit.protobuf.NetworkPb.NeuralNetwork) {
                    return mergeFrom((drillbit.protobuf.NetworkPb.NeuralNetwork) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(drillbit.protobuf.NetworkPb.NeuralNetwork other) {
                if (other == drillbit.protobuf.NetworkPb.NeuralNetwork.getDefaultInstance()) return this;
                if (other.getRegression() != false) {
                    setRegression(other.getRegression());
                }
                if (other.getModel() != com.google.protobuf.ByteString.EMPTY) {
                    setModel(other.getModel());
                }
                if (other.getDims() != 0) {
                    setDims(other.getDims());
                }
                if (!other.labels_.isEmpty()) {
                    if (labels_.isEmpty()) {
                        labels_ = other.labels_;
                        bitField0_ |= 0x00000008;
                    } else {
                        ensureLabelsIsMutable();
                        labels_.addAll(other.labels_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                regression_ = input.readBool();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18: {
                                model_ = input.readBytes();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 26: {
                                java.lang.String s = input.readStringRequireUtf8();
                                ensureLabelsIsMutable();
                                labels_.add(s);
                                break;
                            } // case 26
                            case 32: {
                                dims_ = input.readInt32();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 32
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            /**
             * <code>bool regression = 1;</code>
             *
             * @return The regression.
             */
            @java.lang.Override
            public boolean getRegression() {
                return regression_;
            }

            /**
             * <code>bool regression = 1;</code>
             *
             * @param value The regression to set.
             * @return This builder for chaining.
             */
            public Builder setRegression(boolean value) {

                regression_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>bool regression = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearRegression() {
                bitField0_ = (bitField0_ & ~0x00000001);
                regression_ = false;
                onChanged();
                return this;
            }

            /**
             * <code>bytes model = 2;</code>
             *
             * @return The model.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getModel() {
                return model_;
            }

            /**
             * <code>bytes model = 2;</code>
             *
             * @param value The model to set.
             * @return This builder for chaining.
             */
            public Builder setModel(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                model_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>bytes model = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearModel() {
                bitField0_ = (bitField0_ & ~0x00000002);
                model_ = getDefaultInstance().getModel();
                onChanged();
                return this;
            }

            /**
             * <code>int32 dims = 4;</code>
             *
             * @return The dims.
             */
            @java.lang.Override
            public int getDims() {
                return dims_;
            }

            /**
             * <code>int32 dims = 4;</code>
             *
             * @param value The dims to set.
             * @return This builder for chaining.
             */
            public Builder setDims(int value) {

                dims_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>int32 dims = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearDims() {
                bitField0_ = (bitField0_ & ~0x00000004);
                dims_ = 0;
                onChanged();
                return this;
            }

            private void ensureLabelsIsMutable() {
                if (!labels_.isModifiable()) {
                    labels_ = new com.google.protobuf.LazyStringArrayList(labels_);
                }
                bitField0_ |= 0x00000008;
            }

            /**
             * <code>repeated string labels = 3;</code>
             *
             * @return A list containing the labels.
             */
            public com.google.protobuf.ProtocolStringList
            getLabelsList() {
                labels_.makeImmutable();
                return labels_;
            }

            /**
             * <code>repeated string labels = 3;</code>
             *
             * @return The count of labels.
             */
            public int getLabelsCount() {
                return labels_.size();
            }

            /**
             * <code>repeated string labels = 3;</code>
             *
             * @param index The index of the element to return.
             * @return The labels at the given index.
             */
            public java.lang.String getLabels(int index) {
                return labels_.get(index);
            }

            /**
             * <code>repeated string labels = 3;</code>
             *
             * @param index The index of the value to return.
             * @return The bytes of the labels at the given index.
             */
            public com.google.protobuf.ByteString
            getLabelsBytes(int index) {
                return labels_.getByteString(index);
            }

            /**
             * <code>repeated string labels = 3;</code>
             *
             * @param index The index to set the value at.
             * @param value The labels to set.
             * @return This builder for chaining.
             */
            public Builder setLabels(
                    int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureLabelsIsMutable();
                labels_.set(index, value);
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>repeated string labels = 3;</code>
             *
             * @param value The labels to add.
             * @return This builder for chaining.
             */
            public Builder addLabels(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureLabelsIsMutable();
                labels_.add(value);
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>repeated string labels = 3;</code>
             *
             * @param values The labels to add.
             * @return This builder for chaining.
             */
            public Builder addAllLabels(
                    java.lang.Iterable<java.lang.String> values) {
                ensureLabelsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, labels_);
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>repeated string labels = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearLabels() {
                labels_ =
                        com.google.protobuf.LazyStringArrayList.emptyList();
                bitField0_ = (bitField0_ & ~0x00000008);
                ;
                onChanged();
                return this;
            }

            /**
             * <code>repeated string labels = 3;</code>
             *
             * @param value The bytes of the labels to add.
             * @return This builder for chaining.
             */
            public Builder addLabelsBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                ensureLabelsIsMutable();
                labels_.add(value);
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:drillbit.protobuf.NeuralNetwork)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
