// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protos/drillbit/protobuf/cluster_pb.proto

package drillbit.protobuf;

public final class ClusterPb {
  private ClusterPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KMeansClassifierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:drillbit.protobuf.KMeansClassifier)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool dense = 1;</code>
     * @return The dense.
     */
    boolean getDense();

    /**
     * <code>int32 dims = 2;</code>
     * @return The dims.
     */
    int getDims();

    /**
     * <code>repeated bytes clusterCenters = 3;</code>
     * @return A list containing the clusterCenters.
     */
    java.util.List<com.google.protobuf.ByteString> getClusterCentersList();
    /**
     * <code>repeated bytes clusterCenters = 3;</code>
     * @return The count of clusterCenters.
     */
    int getClusterCentersCount();
    /**
     * <code>repeated bytes clusterCenters = 3;</code>
     * @param index The index of the element to return.
     * @return The clusterCenters at the given index.
     */
    com.google.protobuf.ByteString getClusterCenters(int index);
  }
  /**
   * Protobuf type {@code drillbit.protobuf.KMeansClassifier}
   */
  public static final class KMeansClassifier extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:drillbit.protobuf.KMeansClassifier)
      KMeansClassifierOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KMeansClassifier.newBuilder() to construct.
    private KMeansClassifier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KMeansClassifier() {
      clusterCenters_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KMeansClassifier();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KMeansClassifier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              dense_ = input.readBool();
              break;
            }
            case 16: {

              dims_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                clusterCenters_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              clusterCenters_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          clusterCenters_ = java.util.Collections.unmodifiableList(clusterCenters_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_KMeansClassifier_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_KMeansClassifier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              drillbit.protobuf.ClusterPb.KMeansClassifier.class, drillbit.protobuf.ClusterPb.KMeansClassifier.Builder.class);
    }

    public static final int DENSE_FIELD_NUMBER = 1;
    private boolean dense_;
    /**
     * <code>bool dense = 1;</code>
     * @return The dense.
     */
    @java.lang.Override
    public boolean getDense() {
      return dense_;
    }

    public static final int DIMS_FIELD_NUMBER = 2;
    private int dims_;
    /**
     * <code>int32 dims = 2;</code>
     * @return The dims.
     */
    @java.lang.Override
    public int getDims() {
      return dims_;
    }

    public static final int CLUSTERCENTERS_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> clusterCenters_;
    /**
     * <code>repeated bytes clusterCenters = 3;</code>
     * @return A list containing the clusterCenters.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getClusterCentersList() {
      return clusterCenters_;
    }
    /**
     * <code>repeated bytes clusterCenters = 3;</code>
     * @return The count of clusterCenters.
     */
    public int getClusterCentersCount() {
      return clusterCenters_.size();
    }
    /**
     * <code>repeated bytes clusterCenters = 3;</code>
     * @param index The index of the element to return.
     * @return The clusterCenters at the given index.
     */
    public com.google.protobuf.ByteString getClusterCenters(int index) {
      return clusterCenters_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dense_ != false) {
        output.writeBool(1, dense_);
      }
      if (dims_ != 0) {
        output.writeInt32(2, dims_);
      }
      for (int i = 0; i < clusterCenters_.size(); i++) {
        output.writeBytes(3, clusterCenters_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dense_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, dense_);
      }
      if (dims_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dims_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < clusterCenters_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(clusterCenters_.get(i));
        }
        size += dataSize;
        size += 1 * getClusterCentersList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof drillbit.protobuf.ClusterPb.KMeansClassifier)) {
        return super.equals(obj);
      }
      drillbit.protobuf.ClusterPb.KMeansClassifier other = (drillbit.protobuf.ClusterPb.KMeansClassifier) obj;

      if (getDense()
          != other.getDense()) return false;
      if (getDims()
          != other.getDims()) return false;
      if (!getClusterCentersList()
          .equals(other.getClusterCentersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DENSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDense());
      hash = (37 * hash) + DIMS_FIELD_NUMBER;
      hash = (53 * hash) + getDims();
      if (getClusterCentersCount() > 0) {
        hash = (37 * hash) + CLUSTERCENTERS_FIELD_NUMBER;
        hash = (53 * hash) + getClusterCentersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static drillbit.protobuf.ClusterPb.KMeansClassifier parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.ClusterPb.KMeansClassifier parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.ClusterPb.KMeansClassifier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.ClusterPb.KMeansClassifier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.ClusterPb.KMeansClassifier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.ClusterPb.KMeansClassifier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.ClusterPb.KMeansClassifier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.ClusterPb.KMeansClassifier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.ClusterPb.KMeansClassifier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.ClusterPb.KMeansClassifier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.ClusterPb.KMeansClassifier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.ClusterPb.KMeansClassifier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(drillbit.protobuf.ClusterPb.KMeansClassifier prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code drillbit.protobuf.KMeansClassifier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:drillbit.protobuf.KMeansClassifier)
        drillbit.protobuf.ClusterPb.KMeansClassifierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_KMeansClassifier_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_KMeansClassifier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                drillbit.protobuf.ClusterPb.KMeansClassifier.class, drillbit.protobuf.ClusterPb.KMeansClassifier.Builder.class);
      }

      // Construct using drillbit.protobuf.ClusterPb.KMeansClassifier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dense_ = false;

        dims_ = 0;

        clusterCenters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_KMeansClassifier_descriptor;
      }

      @java.lang.Override
      public drillbit.protobuf.ClusterPb.KMeansClassifier getDefaultInstanceForType() {
        return drillbit.protobuf.ClusterPb.KMeansClassifier.getDefaultInstance();
      }

      @java.lang.Override
      public drillbit.protobuf.ClusterPb.KMeansClassifier build() {
        drillbit.protobuf.ClusterPb.KMeansClassifier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public drillbit.protobuf.ClusterPb.KMeansClassifier buildPartial() {
        drillbit.protobuf.ClusterPb.KMeansClassifier result = new drillbit.protobuf.ClusterPb.KMeansClassifier(this);
        int from_bitField0_ = bitField0_;
        result.dense_ = dense_;
        result.dims_ = dims_;
        if (((bitField0_ & 0x00000001) != 0)) {
          clusterCenters_ = java.util.Collections.unmodifiableList(clusterCenters_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.clusterCenters_ = clusterCenters_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof drillbit.protobuf.ClusterPb.KMeansClassifier) {
          return mergeFrom((drillbit.protobuf.ClusterPb.KMeansClassifier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(drillbit.protobuf.ClusterPb.KMeansClassifier other) {
        if (other == drillbit.protobuf.ClusterPb.KMeansClassifier.getDefaultInstance()) return this;
        if (other.getDense() != false) {
          setDense(other.getDense());
        }
        if (other.getDims() != 0) {
          setDims(other.getDims());
        }
        if (!other.clusterCenters_.isEmpty()) {
          if (clusterCenters_.isEmpty()) {
            clusterCenters_ = other.clusterCenters_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureClusterCentersIsMutable();
            clusterCenters_.addAll(other.clusterCenters_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        drillbit.protobuf.ClusterPb.KMeansClassifier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (drillbit.protobuf.ClusterPb.KMeansClassifier) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean dense_ ;
      /**
       * <code>bool dense = 1;</code>
       * @return The dense.
       */
      @java.lang.Override
      public boolean getDense() {
        return dense_;
      }
      /**
       * <code>bool dense = 1;</code>
       * @param value The dense to set.
       * @return This builder for chaining.
       */
      public Builder setDense(boolean value) {
        
        dense_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool dense = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDense() {
        
        dense_ = false;
        onChanged();
        return this;
      }

      private int dims_ ;
      /**
       * <code>int32 dims = 2;</code>
       * @return The dims.
       */
      @java.lang.Override
      public int getDims() {
        return dims_;
      }
      /**
       * <code>int32 dims = 2;</code>
       * @param value The dims to set.
       * @return This builder for chaining.
       */
      public Builder setDims(int value) {
        
        dims_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dims = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDims() {
        
        dims_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> clusterCenters_ = java.util.Collections.emptyList();
      private void ensureClusterCentersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          clusterCenters_ = new java.util.ArrayList<com.google.protobuf.ByteString>(clusterCenters_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes clusterCenters = 3;</code>
       * @return A list containing the clusterCenters.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getClusterCentersList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(clusterCenters_) : clusterCenters_;
      }
      /**
       * <code>repeated bytes clusterCenters = 3;</code>
       * @return The count of clusterCenters.
       */
      public int getClusterCentersCount() {
        return clusterCenters_.size();
      }
      /**
       * <code>repeated bytes clusterCenters = 3;</code>
       * @param index The index of the element to return.
       * @return The clusterCenters at the given index.
       */
      public com.google.protobuf.ByteString getClusterCenters(int index) {
        return clusterCenters_.get(index);
      }
      /**
       * <code>repeated bytes clusterCenters = 3;</code>
       * @param index The index to set the value at.
       * @param value The clusterCenters to set.
       * @return This builder for chaining.
       */
      public Builder setClusterCenters(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClusterCentersIsMutable();
        clusterCenters_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes clusterCenters = 3;</code>
       * @param value The clusterCenters to add.
       * @return This builder for chaining.
       */
      public Builder addClusterCenters(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClusterCentersIsMutable();
        clusterCenters_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes clusterCenters = 3;</code>
       * @param values The clusterCenters to add.
       * @return This builder for chaining.
       */
      public Builder addAllClusterCenters(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureClusterCentersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, clusterCenters_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes clusterCenters = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClusterCenters() {
        clusterCenters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:drillbit.protobuf.KMeansClassifier)
    }

    // @@protoc_insertion_point(class_scope:drillbit.protobuf.KMeansClassifier)
    private static final drillbit.protobuf.ClusterPb.KMeansClassifier DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new drillbit.protobuf.ClusterPb.KMeansClassifier();
    }

    public static drillbit.protobuf.ClusterPb.KMeansClassifier getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KMeansClassifier>
        PARSER = new com.google.protobuf.AbstractParser<KMeansClassifier>() {
      @java.lang.Override
      public KMeansClassifier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KMeansClassifier(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KMeansClassifier> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KMeansClassifier> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public drillbit.protobuf.ClusterPb.KMeansClassifier getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GaussianMixtureModelClassifierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:drillbit.protobuf.GaussianMixtureModelClassifier)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool dense = 1;</code>
     * @return The dense.
     */
    boolean getDense();

    /**
     * <code>int32 dims = 2;</code>
     * @return The dims.
     */
    int getDims();

    /**
     * <code>string covariance_type = 3;</code>
     * @return The covarianceType.
     */
    java.lang.String getCovarianceType();
    /**
     * <code>string covariance_type = 3;</code>
     * @return The bytes for covarianceType.
     */
    com.google.protobuf.ByteString
        getCovarianceTypeBytes();

    /**
     * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
     */
    java.util.List<drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance> 
        getClusterCenterAndVariancesList();
    /**
     * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
     */
    drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance getClusterCenterAndVariances(int index);
    /**
     * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
     */
    int getClusterCenterAndVariancesCount();
    /**
     * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
     */
    java.util.List<? extends drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVarianceOrBuilder> 
        getClusterCenterAndVariancesOrBuilderList();
    /**
     * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
     */
    drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVarianceOrBuilder getClusterCenterAndVariancesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code drillbit.protobuf.GaussianMixtureModelClassifier}
   */
  public static final class GaussianMixtureModelClassifier extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:drillbit.protobuf.GaussianMixtureModelClassifier)
      GaussianMixtureModelClassifierOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GaussianMixtureModelClassifier.newBuilder() to construct.
    private GaussianMixtureModelClassifier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GaussianMixtureModelClassifier() {
      covarianceType_ = "";
      clusterCenterAndVariances_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GaussianMixtureModelClassifier();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GaussianMixtureModelClassifier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              dense_ = input.readBool();
              break;
            }
            case 16: {

              dims_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              covarianceType_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                clusterCenterAndVariances_ = new java.util.ArrayList<drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance>();
                mutable_bitField0_ |= 0x00000001;
              }
              clusterCenterAndVariances_.add(
                  input.readMessage(drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          clusterCenterAndVariances_ = java.util.Collections.unmodifiableList(clusterCenterAndVariances_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.class, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.Builder.class);
    }

    public interface ClusterCenterAndVarianceOrBuilder extends
        // @@protoc_insertion_point(interface_extends:drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>bytes clusterCenter = 2;</code>
       * @return The clusterCenter.
       */
      com.google.protobuf.ByteString getClusterCenter();

      /**
       * <code>bytes variance = 3;</code>
       * @return The variance.
       */
      com.google.protobuf.ByteString getVariance();
    }
    /**
     * Protobuf type {@code drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance}
     */
    public static final class ClusterCenterAndVariance extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance)
        ClusterCenterAndVarianceOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ClusterCenterAndVariance.newBuilder() to construct.
      private ClusterCenterAndVariance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ClusterCenterAndVariance() {
        clusterCenter_ = com.google.protobuf.ByteString.EMPTY;
        variance_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new ClusterCenterAndVariance();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ClusterCenterAndVariance(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {

                clusterCenter_ = input.readBytes();
                break;
              }
              case 26: {

                variance_ = input.readBytes();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_ClusterCenterAndVariance_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_ClusterCenterAndVariance_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.class, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.Builder.class);
      }

      public static final int CLUSTERCENTER_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString clusterCenter_;
      /**
       * <code>bytes clusterCenter = 2;</code>
       * @return The clusterCenter.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getClusterCenter() {
        return clusterCenter_;
      }

      public static final int VARIANCE_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString variance_;
      /**
       * <code>bytes variance = 3;</code>
       * @return The variance.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getVariance() {
        return variance_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!clusterCenter_.isEmpty()) {
          output.writeBytes(2, clusterCenter_);
        }
        if (!variance_.isEmpty()) {
          output.writeBytes(3, variance_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!clusterCenter_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, clusterCenter_);
        }
        if (!variance_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, variance_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance)) {
          return super.equals(obj);
        }
        drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance other = (drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance) obj;

        if (!getClusterCenter()
            .equals(other.getClusterCenter())) return false;
        if (!getVariance()
            .equals(other.getVariance())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CLUSTERCENTER_FIELD_NUMBER;
        hash = (53 * hash) + getClusterCenter().hashCode();
        hash = (37 * hash) + VARIANCE_FIELD_NUMBER;
        hash = (53 * hash) + getVariance().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance)
          drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVarianceOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_ClusterCenterAndVariance_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_ClusterCenterAndVariance_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.class, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.Builder.class);
        }

        // Construct using drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          clusterCenter_ = com.google.protobuf.ByteString.EMPTY;

          variance_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_ClusterCenterAndVariance_descriptor;
        }

        @java.lang.Override
        public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance getDefaultInstanceForType() {
          return drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.getDefaultInstance();
        }

        @java.lang.Override
        public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance build() {
          drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance buildPartial() {
          drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance result = new drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance(this);
          result.clusterCenter_ = clusterCenter_;
          result.variance_ = variance_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance) {
            return mergeFrom((drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance other) {
          if (other == drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.getDefaultInstance()) return this;
          if (other.getClusterCenter() != com.google.protobuf.ByteString.EMPTY) {
            setClusterCenter(other.getClusterCenter());
          }
          if (other.getVariance() != com.google.protobuf.ByteString.EMPTY) {
            setVariance(other.getVariance());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private com.google.protobuf.ByteString clusterCenter_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes clusterCenter = 2;</code>
         * @return The clusterCenter.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getClusterCenter() {
          return clusterCenter_;
        }
        /**
         * <code>bytes clusterCenter = 2;</code>
         * @param value The clusterCenter to set.
         * @return This builder for chaining.
         */
        public Builder setClusterCenter(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          clusterCenter_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes clusterCenter = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearClusterCenter() {
          
          clusterCenter_ = getDefaultInstance().getClusterCenter();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString variance_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes variance = 3;</code>
         * @return The variance.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getVariance() {
          return variance_;
        }
        /**
         * <code>bytes variance = 3;</code>
         * @param value The variance to set.
         * @return This builder for chaining.
         */
        public Builder setVariance(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          variance_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes variance = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearVariance() {
          
          variance_ = getDefaultInstance().getVariance();
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance)
      }

      // @@protoc_insertion_point(class_scope:drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance)
      private static final drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance();
      }

      public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ClusterCenterAndVariance>
          PARSER = new com.google.protobuf.AbstractParser<ClusterCenterAndVariance>() {
        @java.lang.Override
        public ClusterCenterAndVariance parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClusterCenterAndVariance(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ClusterCenterAndVariance> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ClusterCenterAndVariance> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int DENSE_FIELD_NUMBER = 1;
    private boolean dense_;
    /**
     * <code>bool dense = 1;</code>
     * @return The dense.
     */
    @java.lang.Override
    public boolean getDense() {
      return dense_;
    }

    public static final int DIMS_FIELD_NUMBER = 2;
    private int dims_;
    /**
     * <code>int32 dims = 2;</code>
     * @return The dims.
     */
    @java.lang.Override
    public int getDims() {
      return dims_;
    }

    public static final int COVARIANCE_TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object covarianceType_;
    /**
     * <code>string covariance_type = 3;</code>
     * @return The covarianceType.
     */
    @java.lang.Override
    public java.lang.String getCovarianceType() {
      java.lang.Object ref = covarianceType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        covarianceType_ = s;
        return s;
      }
    }
    /**
     * <code>string covariance_type = 3;</code>
     * @return The bytes for covarianceType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCovarianceTypeBytes() {
      java.lang.Object ref = covarianceType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        covarianceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLUSTERCENTERANDVARIANCES_FIELD_NUMBER = 4;
    private java.util.List<drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance> clusterCenterAndVariances_;
    /**
     * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
     */
    @java.lang.Override
    public java.util.List<drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance> getClusterCenterAndVariancesList() {
      return clusterCenterAndVariances_;
    }
    /**
     * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVarianceOrBuilder> 
        getClusterCenterAndVariancesOrBuilderList() {
      return clusterCenterAndVariances_;
    }
    /**
     * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
     */
    @java.lang.Override
    public int getClusterCenterAndVariancesCount() {
      return clusterCenterAndVariances_.size();
    }
    /**
     * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
     */
    @java.lang.Override
    public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance getClusterCenterAndVariances(int index) {
      return clusterCenterAndVariances_.get(index);
    }
    /**
     * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
     */
    @java.lang.Override
    public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVarianceOrBuilder getClusterCenterAndVariancesOrBuilder(
        int index) {
      return clusterCenterAndVariances_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dense_ != false) {
        output.writeBool(1, dense_);
      }
      if (dims_ != 0) {
        output.writeInt32(2, dims_);
      }
      if (!getCovarianceTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, covarianceType_);
      }
      for (int i = 0; i < clusterCenterAndVariances_.size(); i++) {
        output.writeMessage(4, clusterCenterAndVariances_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dense_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, dense_);
      }
      if (dims_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dims_);
      }
      if (!getCovarianceTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, covarianceType_);
      }
      for (int i = 0; i < clusterCenterAndVariances_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, clusterCenterAndVariances_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier)) {
        return super.equals(obj);
      }
      drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier other = (drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier) obj;

      if (getDense()
          != other.getDense()) return false;
      if (getDims()
          != other.getDims()) return false;
      if (!getCovarianceType()
          .equals(other.getCovarianceType())) return false;
      if (!getClusterCenterAndVariancesList()
          .equals(other.getClusterCenterAndVariancesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DENSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDense());
      hash = (37 * hash) + DIMS_FIELD_NUMBER;
      hash = (53 * hash) + getDims();
      hash = (37 * hash) + COVARIANCE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCovarianceType().hashCode();
      if (getClusterCenterAndVariancesCount() > 0) {
        hash = (37 * hash) + CLUSTERCENTERANDVARIANCES_FIELD_NUMBER;
        hash = (53 * hash) + getClusterCenterAndVariancesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code drillbit.protobuf.GaussianMixtureModelClassifier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:drillbit.protobuf.GaussianMixtureModelClassifier)
        drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.class, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.Builder.class);
      }

      // Construct using drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getClusterCenterAndVariancesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dense_ = false;

        dims_ = 0;

        covarianceType_ = "";

        if (clusterCenterAndVariancesBuilder_ == null) {
          clusterCenterAndVariances_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          clusterCenterAndVariancesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return drillbit.protobuf.ClusterPb.internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_descriptor;
      }

      @java.lang.Override
      public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier getDefaultInstanceForType() {
        return drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.getDefaultInstance();
      }

      @java.lang.Override
      public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier build() {
        drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier buildPartial() {
        drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier result = new drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier(this);
        int from_bitField0_ = bitField0_;
        result.dense_ = dense_;
        result.dims_ = dims_;
        result.covarianceType_ = covarianceType_;
        if (clusterCenterAndVariancesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            clusterCenterAndVariances_ = java.util.Collections.unmodifiableList(clusterCenterAndVariances_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.clusterCenterAndVariances_ = clusterCenterAndVariances_;
        } else {
          result.clusterCenterAndVariances_ = clusterCenterAndVariancesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier) {
          return mergeFrom((drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier other) {
        if (other == drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.getDefaultInstance()) return this;
        if (other.getDense() != false) {
          setDense(other.getDense());
        }
        if (other.getDims() != 0) {
          setDims(other.getDims());
        }
        if (!other.getCovarianceType().isEmpty()) {
          covarianceType_ = other.covarianceType_;
          onChanged();
        }
        if (clusterCenterAndVariancesBuilder_ == null) {
          if (!other.clusterCenterAndVariances_.isEmpty()) {
            if (clusterCenterAndVariances_.isEmpty()) {
              clusterCenterAndVariances_ = other.clusterCenterAndVariances_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureClusterCenterAndVariancesIsMutable();
              clusterCenterAndVariances_.addAll(other.clusterCenterAndVariances_);
            }
            onChanged();
          }
        } else {
          if (!other.clusterCenterAndVariances_.isEmpty()) {
            if (clusterCenterAndVariancesBuilder_.isEmpty()) {
              clusterCenterAndVariancesBuilder_.dispose();
              clusterCenterAndVariancesBuilder_ = null;
              clusterCenterAndVariances_ = other.clusterCenterAndVariances_;
              bitField0_ = (bitField0_ & ~0x00000001);
              clusterCenterAndVariancesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getClusterCenterAndVariancesFieldBuilder() : null;
            } else {
              clusterCenterAndVariancesBuilder_.addAllMessages(other.clusterCenterAndVariances_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean dense_ ;
      /**
       * <code>bool dense = 1;</code>
       * @return The dense.
       */
      @java.lang.Override
      public boolean getDense() {
        return dense_;
      }
      /**
       * <code>bool dense = 1;</code>
       * @param value The dense to set.
       * @return This builder for chaining.
       */
      public Builder setDense(boolean value) {
        
        dense_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool dense = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDense() {
        
        dense_ = false;
        onChanged();
        return this;
      }

      private int dims_ ;
      /**
       * <code>int32 dims = 2;</code>
       * @return The dims.
       */
      @java.lang.Override
      public int getDims() {
        return dims_;
      }
      /**
       * <code>int32 dims = 2;</code>
       * @param value The dims to set.
       * @return This builder for chaining.
       */
      public Builder setDims(int value) {
        
        dims_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dims = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDims() {
        
        dims_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object covarianceType_ = "";
      /**
       * <code>string covariance_type = 3;</code>
       * @return The covarianceType.
       */
      public java.lang.String getCovarianceType() {
        java.lang.Object ref = covarianceType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          covarianceType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string covariance_type = 3;</code>
       * @return The bytes for covarianceType.
       */
      public com.google.protobuf.ByteString
          getCovarianceTypeBytes() {
        java.lang.Object ref = covarianceType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          covarianceType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string covariance_type = 3;</code>
       * @param value The covarianceType to set.
       * @return This builder for chaining.
       */
      public Builder setCovarianceType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        covarianceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string covariance_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCovarianceType() {
        
        covarianceType_ = getDefaultInstance().getCovarianceType();
        onChanged();
        return this;
      }
      /**
       * <code>string covariance_type = 3;</code>
       * @param value The bytes for covarianceType to set.
       * @return This builder for chaining.
       */
      public Builder setCovarianceTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        covarianceType_ = value;
        onChanged();
        return this;
      }

      private java.util.List<drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance> clusterCenterAndVariances_ =
        java.util.Collections.emptyList();
      private void ensureClusterCenterAndVariancesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          clusterCenterAndVariances_ = new java.util.ArrayList<drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance>(clusterCenterAndVariances_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.Builder, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVarianceOrBuilder> clusterCenterAndVariancesBuilder_;

      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public java.util.List<drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance> getClusterCenterAndVariancesList() {
        if (clusterCenterAndVariancesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(clusterCenterAndVariances_);
        } else {
          return clusterCenterAndVariancesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public int getClusterCenterAndVariancesCount() {
        if (clusterCenterAndVariancesBuilder_ == null) {
          return clusterCenterAndVariances_.size();
        } else {
          return clusterCenterAndVariancesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance getClusterCenterAndVariances(int index) {
        if (clusterCenterAndVariancesBuilder_ == null) {
          return clusterCenterAndVariances_.get(index);
        } else {
          return clusterCenterAndVariancesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public Builder setClusterCenterAndVariances(
          int index, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance value) {
        if (clusterCenterAndVariancesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClusterCenterAndVariancesIsMutable();
          clusterCenterAndVariances_.set(index, value);
          onChanged();
        } else {
          clusterCenterAndVariancesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public Builder setClusterCenterAndVariances(
          int index, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.Builder builderForValue) {
        if (clusterCenterAndVariancesBuilder_ == null) {
          ensureClusterCenterAndVariancesIsMutable();
          clusterCenterAndVariances_.set(index, builderForValue.build());
          onChanged();
        } else {
          clusterCenterAndVariancesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public Builder addClusterCenterAndVariances(drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance value) {
        if (clusterCenterAndVariancesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClusterCenterAndVariancesIsMutable();
          clusterCenterAndVariances_.add(value);
          onChanged();
        } else {
          clusterCenterAndVariancesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public Builder addClusterCenterAndVariances(
          int index, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance value) {
        if (clusterCenterAndVariancesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClusterCenterAndVariancesIsMutable();
          clusterCenterAndVariances_.add(index, value);
          onChanged();
        } else {
          clusterCenterAndVariancesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public Builder addClusterCenterAndVariances(
          drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.Builder builderForValue) {
        if (clusterCenterAndVariancesBuilder_ == null) {
          ensureClusterCenterAndVariancesIsMutable();
          clusterCenterAndVariances_.add(builderForValue.build());
          onChanged();
        } else {
          clusterCenterAndVariancesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public Builder addClusterCenterAndVariances(
          int index, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.Builder builderForValue) {
        if (clusterCenterAndVariancesBuilder_ == null) {
          ensureClusterCenterAndVariancesIsMutable();
          clusterCenterAndVariances_.add(index, builderForValue.build());
          onChanged();
        } else {
          clusterCenterAndVariancesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public Builder addAllClusterCenterAndVariances(
          java.lang.Iterable<? extends drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance> values) {
        if (clusterCenterAndVariancesBuilder_ == null) {
          ensureClusterCenterAndVariancesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, clusterCenterAndVariances_);
          onChanged();
        } else {
          clusterCenterAndVariancesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public Builder clearClusterCenterAndVariances() {
        if (clusterCenterAndVariancesBuilder_ == null) {
          clusterCenterAndVariances_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          clusterCenterAndVariancesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public Builder removeClusterCenterAndVariances(int index) {
        if (clusterCenterAndVariancesBuilder_ == null) {
          ensureClusterCenterAndVariancesIsMutable();
          clusterCenterAndVariances_.remove(index);
          onChanged();
        } else {
          clusterCenterAndVariancesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.Builder getClusterCenterAndVariancesBuilder(
          int index) {
        return getClusterCenterAndVariancesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVarianceOrBuilder getClusterCenterAndVariancesOrBuilder(
          int index) {
        if (clusterCenterAndVariancesBuilder_ == null) {
          return clusterCenterAndVariances_.get(index);  } else {
          return clusterCenterAndVariancesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public java.util.List<? extends drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVarianceOrBuilder> 
           getClusterCenterAndVariancesOrBuilderList() {
        if (clusterCenterAndVariancesBuilder_ != null) {
          return clusterCenterAndVariancesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(clusterCenterAndVariances_);
        }
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.Builder addClusterCenterAndVariancesBuilder() {
        return getClusterCenterAndVariancesFieldBuilder().addBuilder(
            drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.getDefaultInstance());
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.Builder addClusterCenterAndVariancesBuilder(
          int index) {
        return getClusterCenterAndVariancesFieldBuilder().addBuilder(
            index, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.getDefaultInstance());
      }
      /**
       * <code>repeated .drillbit.protobuf.GaussianMixtureModelClassifier.ClusterCenterAndVariance ClusterCenterAndVariances = 4;</code>
       */
      public java.util.List<drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.Builder> 
           getClusterCenterAndVariancesBuilderList() {
        return getClusterCenterAndVariancesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.Builder, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVarianceOrBuilder> 
          getClusterCenterAndVariancesFieldBuilder() {
        if (clusterCenterAndVariancesBuilder_ == null) {
          clusterCenterAndVariancesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVariance.Builder, drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier.ClusterCenterAndVarianceOrBuilder>(
                  clusterCenterAndVariances_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          clusterCenterAndVariances_ = null;
        }
        return clusterCenterAndVariancesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:drillbit.protobuf.GaussianMixtureModelClassifier)
    }

    // @@protoc_insertion_point(class_scope:drillbit.protobuf.GaussianMixtureModelClassifier)
    private static final drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier();
    }

    public static drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GaussianMixtureModelClassifier>
        PARSER = new com.google.protobuf.AbstractParser<GaussianMixtureModelClassifier>() {
      @java.lang.Override
      public GaussianMixtureModelClassifier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GaussianMixtureModelClassifier(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GaussianMixtureModelClassifier> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GaussianMixtureModelClassifier> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public drillbit.protobuf.ClusterPb.GaussianMixtureModelClassifier getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_drillbit_protobuf_KMeansClassifier_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_drillbit_protobuf_KMeansClassifier_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_ClusterCenterAndVariance_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_ClusterCenterAndVariance_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3resources/protos/drillbit/protobuf/clu" +
      "ster_pb.proto\022\021drillbit.protobuf\"G\n\020KMea" +
      "nsClassifier\022\r\n\005dense\030\001 \001(\010\022\014\n\004dims\030\002 \001(" +
      "\005\022\026\n\016clusterCenters\030\003 \003(\014\"\212\002\n\036GaussianMi" +
      "xtureModelClassifier\022\r\n\005dense\030\001 \001(\010\022\014\n\004d" +
      "ims\030\002 \001(\005\022\027\n\017covariance_type\030\003 \001(\t\022m\n\031Cl" +
      "usterCenterAndVariances\030\004 \003(\0132J.drillbit" +
      ".protobuf.GaussianMixtureModelClassifier" +
      ".ClusterCenterAndVariance\032C\n\030ClusterCent" +
      "erAndVariance\022\025\n\rclusterCenter\030\002 \001(\014\022\020\n\010" +
      "variance\030\003 \001(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_drillbit_protobuf_KMeansClassifier_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_drillbit_protobuf_KMeansClassifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_drillbit_protobuf_KMeansClassifier_descriptor,
        new java.lang.String[] { "Dense", "Dims", "ClusterCenters", });
    internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_descriptor,
        new java.lang.String[] { "Dense", "Dims", "CovarianceType", "ClusterCenterAndVariances", });
    internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_ClusterCenterAndVariance_descriptor =
      internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_descriptor.getNestedTypes().get(0);
    internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_ClusterCenterAndVariance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_drillbit_protobuf_GaussianMixtureModelClassifier_ClusterCenterAndVariance_descriptor,
        new java.lang.String[] { "ClusterCenter", "Variance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
