// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/neighbors_pb.proto

package drillbit.protobuf;

public final class NeighborsPb {
  private NeighborsPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KNeighborsClassifierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:drillbit.protobuf.KNeighborsClassifier)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool dense = 1;</code>
     * @return The dense.
     */
    boolean getDense();

    /**
     * <code>int32 dims = 2;</code>
     * @return The dims.
     */
    int getDims();

    /**
     * <code>int32 k = 3;</code>
     * @return The k.
     */
    int getK();

    /**
     * <code>string distanceOptions = 4;</code>
     * @return The distanceOptions.
     */
    java.lang.String getDistanceOptions();
    /**
     * <code>string distanceOptions = 4;</code>
     * @return The bytes for distanceOptions.
     */
    com.google.protobuf.ByteString
        getDistanceOptionsBytes();

    /**
     * <code>string weightOptions = 5;</code>
     * @return The weightOptions.
     */
    java.lang.String getWeightOptions();
    /**
     * <code>string weightOptions = 5;</code>
     * @return The bytes for weightOptions.
     */
    com.google.protobuf.ByteString
        getWeightOptionsBytes();

    /**
     * <code>string solverOptions = 6;</code>
     * @return The solverOptions.
     */
    java.lang.String getSolverOptions();
    /**
     * <code>string solverOptions = 6;</code>
     * @return The bytes for solverOptions.
     */
    com.google.protobuf.ByteString
        getSolverOptionsBytes();

    /**
     * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
     */
    java.util.List<drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates> 
        getLabel2CoordinatesList();
    /**
     * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
     */
    drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates getLabel2Coordinates(int index);
    /**
     * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
     */
    int getLabel2CoordinatesCount();
    /**
     * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
     */
    java.util.List<? extends drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinatesOrBuilder> 
        getLabel2CoordinatesOrBuilderList();
    /**
     * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
     */
    drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinatesOrBuilder getLabel2CoordinatesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code drillbit.protobuf.KNeighborsClassifier}
   */
  public static final class KNeighborsClassifier extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:drillbit.protobuf.KNeighborsClassifier)
      KNeighborsClassifierOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KNeighborsClassifier.newBuilder() to construct.
    private KNeighborsClassifier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KNeighborsClassifier() {
      distanceOptions_ = "";
      weightOptions_ = "";
      solverOptions_ = "";
      label2Coordinates_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KNeighborsClassifier();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KNeighborsClassifier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              dense_ = input.readBool();
              break;
            }
            case 16: {

              dims_ = input.readInt32();
              break;
            }
            case 24: {

              k_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              distanceOptions_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              weightOptions_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              solverOptions_ = s;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                label2Coordinates_ = new java.util.ArrayList<drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates>();
                mutable_bitField0_ |= 0x00000001;
              }
              label2Coordinates_.add(
                  input.readMessage(drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          label2Coordinates_ = java.util.Collections.unmodifiableList(label2Coordinates_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return drillbit.protobuf.NeighborsPb.internal_static_drillbit_protobuf_KNeighborsClassifier_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return drillbit.protobuf.NeighborsPb.internal_static_drillbit_protobuf_KNeighborsClassifier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              drillbit.protobuf.NeighborsPb.KNeighborsClassifier.class, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.Builder.class);
    }

    public interface LabelAndCoordinatesOrBuilder extends
        // @@protoc_insertion_point(interface_extends:drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string label = 1;</code>
       * @return The label.
       */
      java.lang.String getLabel();
      /**
       * <code>string label = 1;</code>
       * @return The bytes for label.
       */
      com.google.protobuf.ByteString
          getLabelBytes();

      /**
       * <code>bytes coordinates = 2;</code>
       * @return The coordinates.
       */
      com.google.protobuf.ByteString getCoordinates();
    }
    /**
     * Protobuf type {@code drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates}
     */
    public static final class LabelAndCoordinates extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates)
        LabelAndCoordinatesOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use LabelAndCoordinates.newBuilder() to construct.
      private LabelAndCoordinates(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private LabelAndCoordinates() {
        label_ = "";
        coordinates_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new LabelAndCoordinates();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private LabelAndCoordinates(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                label_ = s;
                break;
              }
              case 18: {

                coordinates_ = input.readBytes();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return drillbit.protobuf.NeighborsPb.internal_static_drillbit_protobuf_KNeighborsClassifier_LabelAndCoordinates_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return drillbit.protobuf.NeighborsPb.internal_static_drillbit_protobuf_KNeighborsClassifier_LabelAndCoordinates_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.class, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.Builder.class);
      }

      public static final int LABEL_FIELD_NUMBER = 1;
      private volatile java.lang.Object label_;
      /**
       * <code>string label = 1;</code>
       * @return The label.
       */
      @java.lang.Override
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        }
      }
      /**
       * <code>string label = 1;</code>
       * @return The bytes for label.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int COORDINATES_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString coordinates_;
      /**
       * <code>bytes coordinates = 2;</code>
       * @return The coordinates.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCoordinates() {
        return coordinates_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getLabelBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, label_);
        }
        if (!coordinates_.isEmpty()) {
          output.writeBytes(2, coordinates_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getLabelBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, label_);
        }
        if (!coordinates_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, coordinates_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates)) {
          return super.equals(obj);
        }
        drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates other = (drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates) obj;

        if (!getLabel()
            .equals(other.getLabel())) return false;
        if (!getCoordinates()
            .equals(other.getCoordinates())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + LABEL_FIELD_NUMBER;
        hash = (53 * hash) + getLabel().hashCode();
        hash = (37 * hash) + COORDINATES_FIELD_NUMBER;
        hash = (53 * hash) + getCoordinates().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates)
          drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinatesOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return drillbit.protobuf.NeighborsPb.internal_static_drillbit_protobuf_KNeighborsClassifier_LabelAndCoordinates_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return drillbit.protobuf.NeighborsPb.internal_static_drillbit_protobuf_KNeighborsClassifier_LabelAndCoordinates_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.class, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.Builder.class);
        }

        // Construct using drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          label_ = "";

          coordinates_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return drillbit.protobuf.NeighborsPb.internal_static_drillbit_protobuf_KNeighborsClassifier_LabelAndCoordinates_descriptor;
        }

        @java.lang.Override
        public drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates getDefaultInstanceForType() {
          return drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.getDefaultInstance();
        }

        @java.lang.Override
        public drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates build() {
          drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates buildPartial() {
          drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates result = new drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates(this);
          result.label_ = label_;
          result.coordinates_ = coordinates_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates) {
            return mergeFrom((drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates other) {
          if (other == drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.getDefaultInstance()) return this;
          if (!other.getLabel().isEmpty()) {
            label_ = other.label_;
            onChanged();
          }
          if (other.getCoordinates() != com.google.protobuf.ByteString.EMPTY) {
            setCoordinates(other.getCoordinates());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object label_ = "";
        /**
         * <code>string label = 1;</code>
         * @return The label.
         */
        public java.lang.String getLabel() {
          java.lang.Object ref = label_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            label_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string label = 1;</code>
         * @return The bytes for label.
         */
        public com.google.protobuf.ByteString
            getLabelBytes() {
          java.lang.Object ref = label_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            label_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string label = 1;</code>
         * @param value The label to set.
         * @return This builder for chaining.
         */
        public Builder setLabel(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          label_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string label = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearLabel() {
          
          label_ = getDefaultInstance().getLabel();
          onChanged();
          return this;
        }
        /**
         * <code>string label = 1;</code>
         * @param value The bytes for label to set.
         * @return This builder for chaining.
         */
        public Builder setLabelBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          label_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString coordinates_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes coordinates = 2;</code>
         * @return The coordinates.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getCoordinates() {
          return coordinates_;
        }
        /**
         * <code>bytes coordinates = 2;</code>
         * @param value The coordinates to set.
         * @return This builder for chaining.
         */
        public Builder setCoordinates(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          coordinates_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes coordinates = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearCoordinates() {
          
          coordinates_ = getDefaultInstance().getCoordinates();
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates)
      }

      // @@protoc_insertion_point(class_scope:drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates)
      private static final drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates();
      }

      public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<LabelAndCoordinates>
          PARSER = new com.google.protobuf.AbstractParser<LabelAndCoordinates>() {
        @java.lang.Override
        public LabelAndCoordinates parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new LabelAndCoordinates(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<LabelAndCoordinates> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<LabelAndCoordinates> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int DENSE_FIELD_NUMBER = 1;
    private boolean dense_;
    /**
     * <code>bool dense = 1;</code>
     * @return The dense.
     */
    @java.lang.Override
    public boolean getDense() {
      return dense_;
    }

    public static final int DIMS_FIELD_NUMBER = 2;
    private int dims_;
    /**
     * <code>int32 dims = 2;</code>
     * @return The dims.
     */
    @java.lang.Override
    public int getDims() {
      return dims_;
    }

    public static final int K_FIELD_NUMBER = 3;
    private int k_;
    /**
     * <code>int32 k = 3;</code>
     * @return The k.
     */
    @java.lang.Override
    public int getK() {
      return k_;
    }

    public static final int DISTANCEOPTIONS_FIELD_NUMBER = 4;
    private volatile java.lang.Object distanceOptions_;
    /**
     * <code>string distanceOptions = 4;</code>
     * @return The distanceOptions.
     */
    @java.lang.Override
    public java.lang.String getDistanceOptions() {
      java.lang.Object ref = distanceOptions_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        distanceOptions_ = s;
        return s;
      }
    }
    /**
     * <code>string distanceOptions = 4;</code>
     * @return The bytes for distanceOptions.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDistanceOptionsBytes() {
      java.lang.Object ref = distanceOptions_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        distanceOptions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEIGHTOPTIONS_FIELD_NUMBER = 5;
    private volatile java.lang.Object weightOptions_;
    /**
     * <code>string weightOptions = 5;</code>
     * @return The weightOptions.
     */
    @java.lang.Override
    public java.lang.String getWeightOptions() {
      java.lang.Object ref = weightOptions_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weightOptions_ = s;
        return s;
      }
    }
    /**
     * <code>string weightOptions = 5;</code>
     * @return The bytes for weightOptions.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWeightOptionsBytes() {
      java.lang.Object ref = weightOptions_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weightOptions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOLVEROPTIONS_FIELD_NUMBER = 6;
    private volatile java.lang.Object solverOptions_;
    /**
     * <code>string solverOptions = 6;</code>
     * @return The solverOptions.
     */
    @java.lang.Override
    public java.lang.String getSolverOptions() {
      java.lang.Object ref = solverOptions_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        solverOptions_ = s;
        return s;
      }
    }
    /**
     * <code>string solverOptions = 6;</code>
     * @return The bytes for solverOptions.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSolverOptionsBytes() {
      java.lang.Object ref = solverOptions_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        solverOptions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABEL2COORDINATES_FIELD_NUMBER = 7;
    private java.util.List<drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates> label2Coordinates_;
    /**
     * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
     */
    @java.lang.Override
    public java.util.List<drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates> getLabel2CoordinatesList() {
      return label2Coordinates_;
    }
    /**
     * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
     */
    @java.lang.Override
    public java.util.List<? extends drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinatesOrBuilder> 
        getLabel2CoordinatesOrBuilderList() {
      return label2Coordinates_;
    }
    /**
     * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
     */
    @java.lang.Override
    public int getLabel2CoordinatesCount() {
      return label2Coordinates_.size();
    }
    /**
     * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
     */
    @java.lang.Override
    public drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates getLabel2Coordinates(int index) {
      return label2Coordinates_.get(index);
    }
    /**
     * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
     */
    @java.lang.Override
    public drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinatesOrBuilder getLabel2CoordinatesOrBuilder(
        int index) {
      return label2Coordinates_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dense_ != false) {
        output.writeBool(1, dense_);
      }
      if (dims_ != 0) {
        output.writeInt32(2, dims_);
      }
      if (k_ != 0) {
        output.writeInt32(3, k_);
      }
      if (!getDistanceOptionsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, distanceOptions_);
      }
      if (!getWeightOptionsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, weightOptions_);
      }
      if (!getSolverOptionsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, solverOptions_);
      }
      for (int i = 0; i < label2Coordinates_.size(); i++) {
        output.writeMessage(7, label2Coordinates_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dense_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, dense_);
      }
      if (dims_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dims_);
      }
      if (k_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, k_);
      }
      if (!getDistanceOptionsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, distanceOptions_);
      }
      if (!getWeightOptionsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, weightOptions_);
      }
      if (!getSolverOptionsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, solverOptions_);
      }
      for (int i = 0; i < label2Coordinates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, label2Coordinates_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof drillbit.protobuf.NeighborsPb.KNeighborsClassifier)) {
        return super.equals(obj);
      }
      drillbit.protobuf.NeighborsPb.KNeighborsClassifier other = (drillbit.protobuf.NeighborsPb.KNeighborsClassifier) obj;

      if (getDense()
          != other.getDense()) return false;
      if (getDims()
          != other.getDims()) return false;
      if (getK()
          != other.getK()) return false;
      if (!getDistanceOptions()
          .equals(other.getDistanceOptions())) return false;
      if (!getWeightOptions()
          .equals(other.getWeightOptions())) return false;
      if (!getSolverOptions()
          .equals(other.getSolverOptions())) return false;
      if (!getLabel2CoordinatesList()
          .equals(other.getLabel2CoordinatesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DENSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDense());
      hash = (37 * hash) + DIMS_FIELD_NUMBER;
      hash = (53 * hash) + getDims();
      hash = (37 * hash) + K_FIELD_NUMBER;
      hash = (53 * hash) + getK();
      hash = (37 * hash) + DISTANCEOPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getDistanceOptions().hashCode();
      hash = (37 * hash) + WEIGHTOPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getWeightOptions().hashCode();
      hash = (37 * hash) + SOLVEROPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getSolverOptions().hashCode();
      if (getLabel2CoordinatesCount() > 0) {
        hash = (37 * hash) + LABEL2COORDINATES_FIELD_NUMBER;
        hash = (53 * hash) + getLabel2CoordinatesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(drillbit.protobuf.NeighborsPb.KNeighborsClassifier prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code drillbit.protobuf.KNeighborsClassifier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:drillbit.protobuf.KNeighborsClassifier)
        drillbit.protobuf.NeighborsPb.KNeighborsClassifierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return drillbit.protobuf.NeighborsPb.internal_static_drillbit_protobuf_KNeighborsClassifier_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return drillbit.protobuf.NeighborsPb.internal_static_drillbit_protobuf_KNeighborsClassifier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                drillbit.protobuf.NeighborsPb.KNeighborsClassifier.class, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.Builder.class);
      }

      // Construct using drillbit.protobuf.NeighborsPb.KNeighborsClassifier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLabel2CoordinatesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dense_ = false;

        dims_ = 0;

        k_ = 0;

        distanceOptions_ = "";

        weightOptions_ = "";

        solverOptions_ = "";

        if (label2CoordinatesBuilder_ == null) {
          label2Coordinates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          label2CoordinatesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return drillbit.protobuf.NeighborsPb.internal_static_drillbit_protobuf_KNeighborsClassifier_descriptor;
      }

      @java.lang.Override
      public drillbit.protobuf.NeighborsPb.KNeighborsClassifier getDefaultInstanceForType() {
        return drillbit.protobuf.NeighborsPb.KNeighborsClassifier.getDefaultInstance();
      }

      @java.lang.Override
      public drillbit.protobuf.NeighborsPb.KNeighborsClassifier build() {
        drillbit.protobuf.NeighborsPb.KNeighborsClassifier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public drillbit.protobuf.NeighborsPb.KNeighborsClassifier buildPartial() {
        drillbit.protobuf.NeighborsPb.KNeighborsClassifier result = new drillbit.protobuf.NeighborsPb.KNeighborsClassifier(this);
        int from_bitField0_ = bitField0_;
        result.dense_ = dense_;
        result.dims_ = dims_;
        result.k_ = k_;
        result.distanceOptions_ = distanceOptions_;
        result.weightOptions_ = weightOptions_;
        result.solverOptions_ = solverOptions_;
        if (label2CoordinatesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            label2Coordinates_ = java.util.Collections.unmodifiableList(label2Coordinates_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.label2Coordinates_ = label2Coordinates_;
        } else {
          result.label2Coordinates_ = label2CoordinatesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof drillbit.protobuf.NeighborsPb.KNeighborsClassifier) {
          return mergeFrom((drillbit.protobuf.NeighborsPb.KNeighborsClassifier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(drillbit.protobuf.NeighborsPb.KNeighborsClassifier other) {
        if (other == drillbit.protobuf.NeighborsPb.KNeighborsClassifier.getDefaultInstance()) return this;
        if (other.getDense() != false) {
          setDense(other.getDense());
        }
        if (other.getDims() != 0) {
          setDims(other.getDims());
        }
        if (other.getK() != 0) {
          setK(other.getK());
        }
        if (!other.getDistanceOptions().isEmpty()) {
          distanceOptions_ = other.distanceOptions_;
          onChanged();
        }
        if (!other.getWeightOptions().isEmpty()) {
          weightOptions_ = other.weightOptions_;
          onChanged();
        }
        if (!other.getSolverOptions().isEmpty()) {
          solverOptions_ = other.solverOptions_;
          onChanged();
        }
        if (label2CoordinatesBuilder_ == null) {
          if (!other.label2Coordinates_.isEmpty()) {
            if (label2Coordinates_.isEmpty()) {
              label2Coordinates_ = other.label2Coordinates_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLabel2CoordinatesIsMutable();
              label2Coordinates_.addAll(other.label2Coordinates_);
            }
            onChanged();
          }
        } else {
          if (!other.label2Coordinates_.isEmpty()) {
            if (label2CoordinatesBuilder_.isEmpty()) {
              label2CoordinatesBuilder_.dispose();
              label2CoordinatesBuilder_ = null;
              label2Coordinates_ = other.label2Coordinates_;
              bitField0_ = (bitField0_ & ~0x00000001);
              label2CoordinatesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLabel2CoordinatesFieldBuilder() : null;
            } else {
              label2CoordinatesBuilder_.addAllMessages(other.label2Coordinates_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        drillbit.protobuf.NeighborsPb.KNeighborsClassifier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (drillbit.protobuf.NeighborsPb.KNeighborsClassifier) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean dense_ ;
      /**
       * <code>bool dense = 1;</code>
       * @return The dense.
       */
      @java.lang.Override
      public boolean getDense() {
        return dense_;
      }
      /**
       * <code>bool dense = 1;</code>
       * @param value The dense to set.
       * @return This builder for chaining.
       */
      public Builder setDense(boolean value) {
        
        dense_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool dense = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDense() {
        
        dense_ = false;
        onChanged();
        return this;
      }

      private int dims_ ;
      /**
       * <code>int32 dims = 2;</code>
       * @return The dims.
       */
      @java.lang.Override
      public int getDims() {
        return dims_;
      }
      /**
       * <code>int32 dims = 2;</code>
       * @param value The dims to set.
       * @return This builder for chaining.
       */
      public Builder setDims(int value) {
        
        dims_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dims = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDims() {
        
        dims_ = 0;
        onChanged();
        return this;
      }

      private int k_ ;
      /**
       * <code>int32 k = 3;</code>
       * @return The k.
       */
      @java.lang.Override
      public int getK() {
        return k_;
      }
      /**
       * <code>int32 k = 3;</code>
       * @param value The k to set.
       * @return This builder for chaining.
       */
      public Builder setK(int value) {
        
        k_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 k = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearK() {
        
        k_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object distanceOptions_ = "";
      /**
       * <code>string distanceOptions = 4;</code>
       * @return The distanceOptions.
       */
      public java.lang.String getDistanceOptions() {
        java.lang.Object ref = distanceOptions_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          distanceOptions_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string distanceOptions = 4;</code>
       * @return The bytes for distanceOptions.
       */
      public com.google.protobuf.ByteString
          getDistanceOptionsBytes() {
        java.lang.Object ref = distanceOptions_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          distanceOptions_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string distanceOptions = 4;</code>
       * @param value The distanceOptions to set.
       * @return This builder for chaining.
       */
      public Builder setDistanceOptions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        distanceOptions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string distanceOptions = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDistanceOptions() {
        
        distanceOptions_ = getDefaultInstance().getDistanceOptions();
        onChanged();
        return this;
      }
      /**
       * <code>string distanceOptions = 4;</code>
       * @param value The bytes for distanceOptions to set.
       * @return This builder for chaining.
       */
      public Builder setDistanceOptionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        distanceOptions_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object weightOptions_ = "";
      /**
       * <code>string weightOptions = 5;</code>
       * @return The weightOptions.
       */
      public java.lang.String getWeightOptions() {
        java.lang.Object ref = weightOptions_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          weightOptions_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string weightOptions = 5;</code>
       * @return The bytes for weightOptions.
       */
      public com.google.protobuf.ByteString
          getWeightOptionsBytes() {
        java.lang.Object ref = weightOptions_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          weightOptions_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string weightOptions = 5;</code>
       * @param value The weightOptions to set.
       * @return This builder for chaining.
       */
      public Builder setWeightOptions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weightOptions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string weightOptions = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeightOptions() {
        
        weightOptions_ = getDefaultInstance().getWeightOptions();
        onChanged();
        return this;
      }
      /**
       * <code>string weightOptions = 5;</code>
       * @param value The bytes for weightOptions to set.
       * @return This builder for chaining.
       */
      public Builder setWeightOptionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weightOptions_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object solverOptions_ = "";
      /**
       * <code>string solverOptions = 6;</code>
       * @return The solverOptions.
       */
      public java.lang.String getSolverOptions() {
        java.lang.Object ref = solverOptions_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          solverOptions_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string solverOptions = 6;</code>
       * @return The bytes for solverOptions.
       */
      public com.google.protobuf.ByteString
          getSolverOptionsBytes() {
        java.lang.Object ref = solverOptions_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          solverOptions_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string solverOptions = 6;</code>
       * @param value The solverOptions to set.
       * @return This builder for chaining.
       */
      public Builder setSolverOptions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        solverOptions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string solverOptions = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSolverOptions() {
        
        solverOptions_ = getDefaultInstance().getSolverOptions();
        onChanged();
        return this;
      }
      /**
       * <code>string solverOptions = 6;</code>
       * @param value The bytes for solverOptions to set.
       * @return This builder for chaining.
       */
      public Builder setSolverOptionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        solverOptions_ = value;
        onChanged();
        return this;
      }

      private java.util.List<drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates> label2Coordinates_ =
        java.util.Collections.emptyList();
      private void ensureLabel2CoordinatesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          label2Coordinates_ = new java.util.ArrayList<drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates>(label2Coordinates_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.Builder, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinatesOrBuilder> label2CoordinatesBuilder_;

      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public java.util.List<drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates> getLabel2CoordinatesList() {
        if (label2CoordinatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(label2Coordinates_);
        } else {
          return label2CoordinatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public int getLabel2CoordinatesCount() {
        if (label2CoordinatesBuilder_ == null) {
          return label2Coordinates_.size();
        } else {
          return label2CoordinatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates getLabel2Coordinates(int index) {
        if (label2CoordinatesBuilder_ == null) {
          return label2Coordinates_.get(index);
        } else {
          return label2CoordinatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public Builder setLabel2Coordinates(
          int index, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates value) {
        if (label2CoordinatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabel2CoordinatesIsMutable();
          label2Coordinates_.set(index, value);
          onChanged();
        } else {
          label2CoordinatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public Builder setLabel2Coordinates(
          int index, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.Builder builderForValue) {
        if (label2CoordinatesBuilder_ == null) {
          ensureLabel2CoordinatesIsMutable();
          label2Coordinates_.set(index, builderForValue.build());
          onChanged();
        } else {
          label2CoordinatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public Builder addLabel2Coordinates(drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates value) {
        if (label2CoordinatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabel2CoordinatesIsMutable();
          label2Coordinates_.add(value);
          onChanged();
        } else {
          label2CoordinatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public Builder addLabel2Coordinates(
          int index, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates value) {
        if (label2CoordinatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabel2CoordinatesIsMutable();
          label2Coordinates_.add(index, value);
          onChanged();
        } else {
          label2CoordinatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public Builder addLabel2Coordinates(
          drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.Builder builderForValue) {
        if (label2CoordinatesBuilder_ == null) {
          ensureLabel2CoordinatesIsMutable();
          label2Coordinates_.add(builderForValue.build());
          onChanged();
        } else {
          label2CoordinatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public Builder addLabel2Coordinates(
          int index, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.Builder builderForValue) {
        if (label2CoordinatesBuilder_ == null) {
          ensureLabel2CoordinatesIsMutable();
          label2Coordinates_.add(index, builderForValue.build());
          onChanged();
        } else {
          label2CoordinatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public Builder addAllLabel2Coordinates(
          java.lang.Iterable<? extends drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates> values) {
        if (label2CoordinatesBuilder_ == null) {
          ensureLabel2CoordinatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, label2Coordinates_);
          onChanged();
        } else {
          label2CoordinatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public Builder clearLabel2Coordinates() {
        if (label2CoordinatesBuilder_ == null) {
          label2Coordinates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          label2CoordinatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public Builder removeLabel2Coordinates(int index) {
        if (label2CoordinatesBuilder_ == null) {
          ensureLabel2CoordinatesIsMutable();
          label2Coordinates_.remove(index);
          onChanged();
        } else {
          label2CoordinatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.Builder getLabel2CoordinatesBuilder(
          int index) {
        return getLabel2CoordinatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinatesOrBuilder getLabel2CoordinatesOrBuilder(
          int index) {
        if (label2CoordinatesBuilder_ == null) {
          return label2Coordinates_.get(index);  } else {
          return label2CoordinatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public java.util.List<? extends drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinatesOrBuilder> 
           getLabel2CoordinatesOrBuilderList() {
        if (label2CoordinatesBuilder_ != null) {
          return label2CoordinatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(label2Coordinates_);
        }
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.Builder addLabel2CoordinatesBuilder() {
        return getLabel2CoordinatesFieldBuilder().addBuilder(
            drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.getDefaultInstance());
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.Builder addLabel2CoordinatesBuilder(
          int index) {
        return getLabel2CoordinatesFieldBuilder().addBuilder(
            index, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.getDefaultInstance());
      }
      /**
       * <code>repeated .drillbit.protobuf.KNeighborsClassifier.LabelAndCoordinates label2Coordinates = 7;</code>
       */
      public java.util.List<drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.Builder> 
           getLabel2CoordinatesBuilderList() {
        return getLabel2CoordinatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.Builder, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinatesOrBuilder> 
          getLabel2CoordinatesFieldBuilder() {
        if (label2CoordinatesBuilder_ == null) {
          label2CoordinatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinates.Builder, drillbit.protobuf.NeighborsPb.KNeighborsClassifier.LabelAndCoordinatesOrBuilder>(
                  label2Coordinates_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          label2Coordinates_ = null;
        }
        return label2CoordinatesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:drillbit.protobuf.KNeighborsClassifier)
    }

    // @@protoc_insertion_point(class_scope:drillbit.protobuf.KNeighborsClassifier)
    private static final drillbit.protobuf.NeighborsPb.KNeighborsClassifier DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new drillbit.protobuf.NeighborsPb.KNeighborsClassifier();
    }

    public static drillbit.protobuf.NeighborsPb.KNeighborsClassifier getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KNeighborsClassifier>
        PARSER = new com.google.protobuf.AbstractParser<KNeighborsClassifier>() {
      @java.lang.Override
      public KNeighborsClassifier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KNeighborsClassifier(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KNeighborsClassifier> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KNeighborsClassifier> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public drillbit.protobuf.NeighborsPb.KNeighborsClassifier getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_drillbit_protobuf_KNeighborsClassifier_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_drillbit_protobuf_KNeighborsClassifier_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_drillbit_protobuf_KNeighborsClassifier_LabelAndCoordinates_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_drillbit_protobuf_KNeighborsClassifier_LabelAndCoordinates_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/neighbors_pb.proto\022\021drillbit.pro" +
      "tobuf\"\230\002\n\024KNeighborsClassifier\022\r\n\005dense\030" +
      "\001 \001(\010\022\014\n\004dims\030\002 \001(\005\022\t\n\001k\030\003 \001(\005\022\027\n\017distan" +
      "ceOptions\030\004 \001(\t\022\025\n\rweightOptions\030\005 \001(\t\022\025" +
      "\n\rsolverOptions\030\006 \001(\t\022V\n\021label2Coordinat" +
      "es\030\007 \003(\0132;.drillbit.protobuf.KNeighborsC" +
      "lassifier.LabelAndCoordinates\0329\n\023LabelAn" +
      "dCoordinates\022\r\n\005label\030\001 \001(\t\022\023\n\013coordinat" +
      "es\030\002 \001(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_drillbit_protobuf_KNeighborsClassifier_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_drillbit_protobuf_KNeighborsClassifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_drillbit_protobuf_KNeighborsClassifier_descriptor,
        new java.lang.String[] { "Dense", "Dims", "K", "DistanceOptions", "WeightOptions", "SolverOptions", "Label2Coordinates", });
    internal_static_drillbit_protobuf_KNeighborsClassifier_LabelAndCoordinates_descriptor =
      internal_static_drillbit_protobuf_KNeighborsClassifier_descriptor.getNestedTypes().get(0);
    internal_static_drillbit_protobuf_KNeighborsClassifier_LabelAndCoordinates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_drillbit_protobuf_KNeighborsClassifier_LabelAndCoordinates_descriptor,
        new java.lang.String[] { "Label", "Coordinates", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
