// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protos/drillbit/protobuf/regression_pb.proto

package drillbit.protobuf;

public final class RegressionPb {
  private RegressionPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GeneralRegressorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:drillbit.protobuf.GeneralRegressor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool dense = 1;</code>
     * @return The dense.
     */
    boolean getDense();

    /**
     * <code>int32 dims = 2;</code>
     * @return The dims.
     */
    int getDims();

    /**
     * <code>bytes weights = 3;</code>
     * @return The weights.
     */
    com.google.protobuf.ByteString getWeights();
  }
  /**
   * Protobuf type {@code drillbit.protobuf.GeneralRegressor}
   */
  public static final class GeneralRegressor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:drillbit.protobuf.GeneralRegressor)
      GeneralRegressorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GeneralRegressor.newBuilder() to construct.
    private GeneralRegressor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GeneralRegressor() {
      weights_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GeneralRegressor();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GeneralRegressor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              dense_ = input.readBool();
              break;
            }
            case 16: {

              dims_ = input.readInt32();
              break;
            }
            case 26: {

              weights_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_GeneralRegressor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_GeneralRegressor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              drillbit.protobuf.RegressionPb.GeneralRegressor.class, drillbit.protobuf.RegressionPb.GeneralRegressor.Builder.class);
    }

    public static final int DENSE_FIELD_NUMBER = 1;
    private boolean dense_;
    /**
     * <code>bool dense = 1;</code>
     * @return The dense.
     */
    @java.lang.Override
    public boolean getDense() {
      return dense_;
    }

    public static final int DIMS_FIELD_NUMBER = 2;
    private int dims_;
    /**
     * <code>int32 dims = 2;</code>
     * @return The dims.
     */
    @java.lang.Override
    public int getDims() {
      return dims_;
    }

    public static final int WEIGHTS_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString weights_;
    /**
     * <code>bytes weights = 3;</code>
     * @return The weights.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getWeights() {
      return weights_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dense_ != false) {
        output.writeBool(1, dense_);
      }
      if (dims_ != 0) {
        output.writeInt32(2, dims_);
      }
      if (!weights_.isEmpty()) {
        output.writeBytes(3, weights_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dense_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, dense_);
      }
      if (dims_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dims_);
      }
      if (!weights_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, weights_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof drillbit.protobuf.RegressionPb.GeneralRegressor)) {
        return super.equals(obj);
      }
      drillbit.protobuf.RegressionPb.GeneralRegressor other = (drillbit.protobuf.RegressionPb.GeneralRegressor) obj;

      if (getDense()
          != other.getDense()) return false;
      if (getDims()
          != other.getDims()) return false;
      if (!getWeights()
          .equals(other.getWeights())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DENSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDense());
      hash = (37 * hash) + DIMS_FIELD_NUMBER;
      hash = (53 * hash) + getDims();
      hash = (37 * hash) + WEIGHTS_FIELD_NUMBER;
      hash = (53 * hash) + getWeights().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static drillbit.protobuf.RegressionPb.GeneralRegressor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.RegressionPb.GeneralRegressor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.GeneralRegressor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.RegressionPb.GeneralRegressor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.GeneralRegressor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.RegressionPb.GeneralRegressor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.GeneralRegressor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.RegressionPb.GeneralRegressor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.GeneralRegressor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.RegressionPb.GeneralRegressor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.GeneralRegressor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.RegressionPb.GeneralRegressor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(drillbit.protobuf.RegressionPb.GeneralRegressor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code drillbit.protobuf.GeneralRegressor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:drillbit.protobuf.GeneralRegressor)
        drillbit.protobuf.RegressionPb.GeneralRegressorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_GeneralRegressor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_GeneralRegressor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                drillbit.protobuf.RegressionPb.GeneralRegressor.class, drillbit.protobuf.RegressionPb.GeneralRegressor.Builder.class);
      }

      // Construct using drillbit.protobuf.RegressionPb.GeneralRegressor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dense_ = false;

        dims_ = 0;

        weights_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_GeneralRegressor_descriptor;
      }

      @java.lang.Override
      public drillbit.protobuf.RegressionPb.GeneralRegressor getDefaultInstanceForType() {
        return drillbit.protobuf.RegressionPb.GeneralRegressor.getDefaultInstance();
      }

      @java.lang.Override
      public drillbit.protobuf.RegressionPb.GeneralRegressor build() {
        drillbit.protobuf.RegressionPb.GeneralRegressor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public drillbit.protobuf.RegressionPb.GeneralRegressor buildPartial() {
        drillbit.protobuf.RegressionPb.GeneralRegressor result = new drillbit.protobuf.RegressionPb.GeneralRegressor(this);
        result.dense_ = dense_;
        result.dims_ = dims_;
        result.weights_ = weights_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof drillbit.protobuf.RegressionPb.GeneralRegressor) {
          return mergeFrom((drillbit.protobuf.RegressionPb.GeneralRegressor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(drillbit.protobuf.RegressionPb.GeneralRegressor other) {
        if (other == drillbit.protobuf.RegressionPb.GeneralRegressor.getDefaultInstance()) return this;
        if (other.getDense() != false) {
          setDense(other.getDense());
        }
        if (other.getDims() != 0) {
          setDims(other.getDims());
        }
        if (other.getWeights() != com.google.protobuf.ByteString.EMPTY) {
          setWeights(other.getWeights());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        drillbit.protobuf.RegressionPb.GeneralRegressor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (drillbit.protobuf.RegressionPb.GeneralRegressor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean dense_ ;
      /**
       * <code>bool dense = 1;</code>
       * @return The dense.
       */
      @java.lang.Override
      public boolean getDense() {
        return dense_;
      }
      /**
       * <code>bool dense = 1;</code>
       * @param value The dense to set.
       * @return This builder for chaining.
       */
      public Builder setDense(boolean value) {
        
        dense_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool dense = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDense() {
        
        dense_ = false;
        onChanged();
        return this;
      }

      private int dims_ ;
      /**
       * <code>int32 dims = 2;</code>
       * @return The dims.
       */
      @java.lang.Override
      public int getDims() {
        return dims_;
      }
      /**
       * <code>int32 dims = 2;</code>
       * @param value The dims to set.
       * @return This builder for chaining.
       */
      public Builder setDims(int value) {
        
        dims_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dims = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDims() {
        
        dims_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString weights_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes weights = 3;</code>
       * @return The weights.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getWeights() {
        return weights_;
      }
      /**
       * <code>bytes weights = 3;</code>
       * @param value The weights to set.
       * @return This builder for chaining.
       */
      public Builder setWeights(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weights_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes weights = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeights() {
        
        weights_ = getDefaultInstance().getWeights();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:drillbit.protobuf.GeneralRegressor)
    }

    // @@protoc_insertion_point(class_scope:drillbit.protobuf.GeneralRegressor)
    private static final drillbit.protobuf.RegressionPb.GeneralRegressor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new drillbit.protobuf.RegressionPb.GeneralRegressor();
    }

    public static drillbit.protobuf.RegressionPb.GeneralRegressor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GeneralRegressor>
        PARSER = new com.google.protobuf.AbstractParser<GeneralRegressor>() {
      @java.lang.Override
      public GeneralRegressor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GeneralRegressor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GeneralRegressor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GeneralRegressor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public drillbit.protobuf.RegressionPb.GeneralRegressor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DecisionTreeRegressorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:drillbit.protobuf.DecisionTreeRegressor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes root = 1;</code>
     * @return The root.
     */
    com.google.protobuf.ByteString getRoot();
  }
  /**
   * Protobuf type {@code drillbit.protobuf.DecisionTreeRegressor}
   */
  public static final class DecisionTreeRegressor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:drillbit.protobuf.DecisionTreeRegressor)
      DecisionTreeRegressorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DecisionTreeRegressor.newBuilder() to construct.
    private DecisionTreeRegressor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DecisionTreeRegressor() {
      root_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DecisionTreeRegressor();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DecisionTreeRegressor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              root_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_DecisionTreeRegressor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_DecisionTreeRegressor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              drillbit.protobuf.RegressionPb.DecisionTreeRegressor.class, drillbit.protobuf.RegressionPb.DecisionTreeRegressor.Builder.class);
    }

    public static final int ROOT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString root_;
    /**
     * <code>bytes root = 1;</code>
     * @return The root.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRoot() {
      return root_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!root_.isEmpty()) {
        output.writeBytes(1, root_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!root_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, root_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof drillbit.protobuf.RegressionPb.DecisionTreeRegressor)) {
        return super.equals(obj);
      }
      drillbit.protobuf.RegressionPb.DecisionTreeRegressor other = (drillbit.protobuf.RegressionPb.DecisionTreeRegressor) obj;

      if (!getRoot()
          .equals(other.getRoot())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROOT_FIELD_NUMBER;
      hash = (53 * hash) + getRoot().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(drillbit.protobuf.RegressionPb.DecisionTreeRegressor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code drillbit.protobuf.DecisionTreeRegressor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:drillbit.protobuf.DecisionTreeRegressor)
        drillbit.protobuf.RegressionPb.DecisionTreeRegressorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_DecisionTreeRegressor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_DecisionTreeRegressor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                drillbit.protobuf.RegressionPb.DecisionTreeRegressor.class, drillbit.protobuf.RegressionPb.DecisionTreeRegressor.Builder.class);
      }

      // Construct using drillbit.protobuf.RegressionPb.DecisionTreeRegressor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        root_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_DecisionTreeRegressor_descriptor;
      }

      @java.lang.Override
      public drillbit.protobuf.RegressionPb.DecisionTreeRegressor getDefaultInstanceForType() {
        return drillbit.protobuf.RegressionPb.DecisionTreeRegressor.getDefaultInstance();
      }

      @java.lang.Override
      public drillbit.protobuf.RegressionPb.DecisionTreeRegressor build() {
        drillbit.protobuf.RegressionPb.DecisionTreeRegressor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public drillbit.protobuf.RegressionPb.DecisionTreeRegressor buildPartial() {
        drillbit.protobuf.RegressionPb.DecisionTreeRegressor result = new drillbit.protobuf.RegressionPb.DecisionTreeRegressor(this);
        result.root_ = root_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof drillbit.protobuf.RegressionPb.DecisionTreeRegressor) {
          return mergeFrom((drillbit.protobuf.RegressionPb.DecisionTreeRegressor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(drillbit.protobuf.RegressionPb.DecisionTreeRegressor other) {
        if (other == drillbit.protobuf.RegressionPb.DecisionTreeRegressor.getDefaultInstance()) return this;
        if (other.getRoot() != com.google.protobuf.ByteString.EMPTY) {
          setRoot(other.getRoot());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        drillbit.protobuf.RegressionPb.DecisionTreeRegressor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (drillbit.protobuf.RegressionPb.DecisionTreeRegressor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString root_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes root = 1;</code>
       * @return The root.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRoot() {
        return root_;
      }
      /**
       * <code>bytes root = 1;</code>
       * @param value The root to set.
       * @return This builder for chaining.
       */
      public Builder setRoot(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        root_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes root = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoot() {
        
        root_ = getDefaultInstance().getRoot();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:drillbit.protobuf.DecisionTreeRegressor)
    }

    // @@protoc_insertion_point(class_scope:drillbit.protobuf.DecisionTreeRegressor)
    private static final drillbit.protobuf.RegressionPb.DecisionTreeRegressor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new drillbit.protobuf.RegressionPb.DecisionTreeRegressor();
    }

    public static drillbit.protobuf.RegressionPb.DecisionTreeRegressor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DecisionTreeRegressor>
        PARSER = new com.google.protobuf.AbstractParser<DecisionTreeRegressor>() {
      @java.lang.Override
      public DecisionTreeRegressor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DecisionTreeRegressor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DecisionTreeRegressor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DecisionTreeRegressor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public drillbit.protobuf.RegressionPb.DecisionTreeRegressor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RandomForestRegressorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:drillbit.protobuf.RandomForestRegressor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes roots = 1;</code>
     * @return A list containing the roots.
     */
    java.util.List<com.google.protobuf.ByteString> getRootsList();
    /**
     * <code>repeated bytes roots = 1;</code>
     * @return The count of roots.
     */
    int getRootsCount();
    /**
     * <code>repeated bytes roots = 1;</code>
     * @param index The index of the element to return.
     * @return The roots at the given index.
     */
    com.google.protobuf.ByteString getRoots(int index);
  }
  /**
   * Protobuf type {@code drillbit.protobuf.RandomForestRegressor}
   */
  public static final class RandomForestRegressor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:drillbit.protobuf.RandomForestRegressor)
      RandomForestRegressorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RandomForestRegressor.newBuilder() to construct.
    private RandomForestRegressor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RandomForestRegressor() {
      roots_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RandomForestRegressor();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RandomForestRegressor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                roots_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              roots_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          roots_ = java.util.Collections.unmodifiableList(roots_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_RandomForestRegressor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_RandomForestRegressor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              drillbit.protobuf.RegressionPb.RandomForestRegressor.class, drillbit.protobuf.RegressionPb.RandomForestRegressor.Builder.class);
    }

    public static final int ROOTS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> roots_;
    /**
     * <code>repeated bytes roots = 1;</code>
     * @return A list containing the roots.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getRootsList() {
      return roots_;
    }
    /**
     * <code>repeated bytes roots = 1;</code>
     * @return The count of roots.
     */
    public int getRootsCount() {
      return roots_.size();
    }
    /**
     * <code>repeated bytes roots = 1;</code>
     * @param index The index of the element to return.
     * @return The roots at the given index.
     */
    public com.google.protobuf.ByteString getRoots(int index) {
      return roots_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < roots_.size(); i++) {
        output.writeBytes(1, roots_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < roots_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(roots_.get(i));
        }
        size += dataSize;
        size += 1 * getRootsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof drillbit.protobuf.RegressionPb.RandomForestRegressor)) {
        return super.equals(obj);
      }
      drillbit.protobuf.RegressionPb.RandomForestRegressor other = (drillbit.protobuf.RegressionPb.RandomForestRegressor) obj;

      if (!getRootsList()
          .equals(other.getRootsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRootsCount() > 0) {
        hash = (37 * hash) + ROOTS_FIELD_NUMBER;
        hash = (53 * hash) + getRootsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static drillbit.protobuf.RegressionPb.RandomForestRegressor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.RegressionPb.RandomForestRegressor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.RandomForestRegressor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.RegressionPb.RandomForestRegressor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.RandomForestRegressor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.RegressionPb.RandomForestRegressor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.RandomForestRegressor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.RegressionPb.RandomForestRegressor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.RandomForestRegressor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.RegressionPb.RandomForestRegressor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.RegressionPb.RandomForestRegressor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.RegressionPb.RandomForestRegressor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(drillbit.protobuf.RegressionPb.RandomForestRegressor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code drillbit.protobuf.RandomForestRegressor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:drillbit.protobuf.RandomForestRegressor)
        drillbit.protobuf.RegressionPb.RandomForestRegressorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_RandomForestRegressor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_RandomForestRegressor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                drillbit.protobuf.RegressionPb.RandomForestRegressor.class, drillbit.protobuf.RegressionPb.RandomForestRegressor.Builder.class);
      }

      // Construct using drillbit.protobuf.RegressionPb.RandomForestRegressor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        roots_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return drillbit.protobuf.RegressionPb.internal_static_drillbit_protobuf_RandomForestRegressor_descriptor;
      }

      @java.lang.Override
      public drillbit.protobuf.RegressionPb.RandomForestRegressor getDefaultInstanceForType() {
        return drillbit.protobuf.RegressionPb.RandomForestRegressor.getDefaultInstance();
      }

      @java.lang.Override
      public drillbit.protobuf.RegressionPb.RandomForestRegressor build() {
        drillbit.protobuf.RegressionPb.RandomForestRegressor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public drillbit.protobuf.RegressionPb.RandomForestRegressor buildPartial() {
        drillbit.protobuf.RegressionPb.RandomForestRegressor result = new drillbit.protobuf.RegressionPb.RandomForestRegressor(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          roots_ = java.util.Collections.unmodifiableList(roots_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.roots_ = roots_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof drillbit.protobuf.RegressionPb.RandomForestRegressor) {
          return mergeFrom((drillbit.protobuf.RegressionPb.RandomForestRegressor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(drillbit.protobuf.RegressionPb.RandomForestRegressor other) {
        if (other == drillbit.protobuf.RegressionPb.RandomForestRegressor.getDefaultInstance()) return this;
        if (!other.roots_.isEmpty()) {
          if (roots_.isEmpty()) {
            roots_ = other.roots_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRootsIsMutable();
            roots_.addAll(other.roots_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        drillbit.protobuf.RegressionPb.RandomForestRegressor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (drillbit.protobuf.RegressionPb.RandomForestRegressor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> roots_ = java.util.Collections.emptyList();
      private void ensureRootsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          roots_ = new java.util.ArrayList<com.google.protobuf.ByteString>(roots_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes roots = 1;</code>
       * @return A list containing the roots.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getRootsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(roots_) : roots_;
      }
      /**
       * <code>repeated bytes roots = 1;</code>
       * @return The count of roots.
       */
      public int getRootsCount() {
        return roots_.size();
      }
      /**
       * <code>repeated bytes roots = 1;</code>
       * @param index The index of the element to return.
       * @return The roots at the given index.
       */
      public com.google.protobuf.ByteString getRoots(int index) {
        return roots_.get(index);
      }
      /**
       * <code>repeated bytes roots = 1;</code>
       * @param index The index to set the value at.
       * @param value The roots to set.
       * @return This builder for chaining.
       */
      public Builder setRoots(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRootsIsMutable();
        roots_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes roots = 1;</code>
       * @param value The roots to add.
       * @return This builder for chaining.
       */
      public Builder addRoots(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRootsIsMutable();
        roots_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes roots = 1;</code>
       * @param values The roots to add.
       * @return This builder for chaining.
       */
      public Builder addAllRoots(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureRootsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roots_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes roots = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoots() {
        roots_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:drillbit.protobuf.RandomForestRegressor)
    }

    // @@protoc_insertion_point(class_scope:drillbit.protobuf.RandomForestRegressor)
    private static final drillbit.protobuf.RegressionPb.RandomForestRegressor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new drillbit.protobuf.RegressionPb.RandomForestRegressor();
    }

    public static drillbit.protobuf.RegressionPb.RandomForestRegressor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RandomForestRegressor>
        PARSER = new com.google.protobuf.AbstractParser<RandomForestRegressor>() {
      @java.lang.Override
      public RandomForestRegressor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RandomForestRegressor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RandomForestRegressor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RandomForestRegressor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public drillbit.protobuf.RegressionPb.RandomForestRegressor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_drillbit_protobuf_GeneralRegressor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_drillbit_protobuf_GeneralRegressor_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_drillbit_protobuf_DecisionTreeRegressor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_drillbit_protobuf_DecisionTreeRegressor_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_drillbit_protobuf_RandomForestRegressor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_drillbit_protobuf_RandomForestRegressor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6resources/protos/drillbit/protobuf/reg" +
      "ression_pb.proto\022\021drillbit.protobuf\"@\n\020G" +
      "eneralRegressor\022\r\n\005dense\030\001 \001(\010\022\014\n\004dims\030\002" +
      " \001(\005\022\017\n\007weights\030\003 \001(\014\"%\n\025DecisionTreeReg" +
      "ressor\022\014\n\004root\030\001 \001(\014\"&\n\025RandomForestRegr" +
      "essor\022\r\n\005roots\030\001 \003(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_drillbit_protobuf_GeneralRegressor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_drillbit_protobuf_GeneralRegressor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_drillbit_protobuf_GeneralRegressor_descriptor,
        new java.lang.String[] { "Dense", "Dims", "Weights", });
    internal_static_drillbit_protobuf_DecisionTreeRegressor_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_drillbit_protobuf_DecisionTreeRegressor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_drillbit_protobuf_DecisionTreeRegressor_descriptor,
        new java.lang.String[] { "Root", });
    internal_static_drillbit_protobuf_RandomForestRegressor_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_drillbit_protobuf_RandomForestRegressor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_drillbit_protobuf_RandomForestRegressor_descriptor,
        new java.lang.String[] { "Roots", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
