// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/sample_pb.proto

package drillbit.protobuf;

public final class SamplePb {
  private SamplePb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:drillbit.protobuf.Sample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string feature = 1;</code>
     * @return A list containing the feature.
     */
    java.util.List<java.lang.String>
        getFeatureList();
    /**
     * <code>repeated string feature = 1;</code>
     * @return The count of feature.
     */
    int getFeatureCount();
    /**
     * <code>repeated string feature = 1;</code>
     * @param index The index of the element to return.
     * @return The feature at the given index.
     */
    java.lang.String getFeature(int index);
    /**
     * <code>repeated string feature = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the feature at the given index.
     */
    com.google.protobuf.ByteString
        getFeatureBytes(int index);

    /**
     * <code>string target = 2;</code>
     * @return The target.
     */
    java.lang.String getTarget();
    /**
     * <code>string target = 2;</code>
     * @return The bytes for target.
     */
    com.google.protobuf.ByteString
        getTargetBytes();
  }
  /**
   * Protobuf type {@code drillbit.protobuf.Sample}
   */
  public static final class Sample extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:drillbit.protobuf.Sample)
      SampleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Sample.newBuilder() to construct.
    private Sample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sample() {
      feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      target_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Sample();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Sample(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                feature_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              feature_.add(s);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              target_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          feature_ = feature_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return drillbit.protobuf.SamplePb.internal_static_drillbit_protobuf_Sample_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return drillbit.protobuf.SamplePb.internal_static_drillbit_protobuf_Sample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              drillbit.protobuf.SamplePb.Sample.class, drillbit.protobuf.SamplePb.Sample.Builder.class);
    }

    public static final int FEATURE_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList feature_;
    /**
     * <code>repeated string feature = 1;</code>
     * @return A list containing the feature.
     */
    public com.google.protobuf.ProtocolStringList
        getFeatureList() {
      return feature_;
    }
    /**
     * <code>repeated string feature = 1;</code>
     * @return The count of feature.
     */
    public int getFeatureCount() {
      return feature_.size();
    }
    /**
     * <code>repeated string feature = 1;</code>
     * @param index The index of the element to return.
     * @return The feature at the given index.
     */
    public java.lang.String getFeature(int index) {
      return feature_.get(index);
    }
    /**
     * <code>repeated string feature = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the feature at the given index.
     */
    public com.google.protobuf.ByteString
        getFeatureBytes(int index) {
      return feature_.getByteString(index);
    }

    public static final int TARGET_FIELD_NUMBER = 2;
    private volatile java.lang.Object target_;
    /**
     * <code>string target = 2;</code>
     * @return The target.
     */
    @java.lang.Override
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        target_ = s;
        return s;
      }
    }
    /**
     * <code>string target = 2;</code>
     * @return The bytes for target.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < feature_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, feature_.getRaw(i));
      }
      if (!getTargetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, target_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < feature_.size(); i++) {
          dataSize += computeStringSizeNoTag(feature_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFeatureList().size();
      }
      if (!getTargetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, target_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof drillbit.protobuf.SamplePb.Sample)) {
        return super.equals(obj);
      }
      drillbit.protobuf.SamplePb.Sample other = (drillbit.protobuf.SamplePb.Sample) obj;

      if (!getFeatureList()
          .equals(other.getFeatureList())) return false;
      if (!getTarget()
          .equals(other.getTarget())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFeatureCount() > 0) {
        hash = (37 * hash) + FEATURE_FIELD_NUMBER;
        hash = (53 * hash) + getFeatureList().hashCode();
      }
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTarget().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static drillbit.protobuf.SamplePb.Sample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.SamplePb.Sample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.SamplePb.Sample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.SamplePb.Sample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.SamplePb.Sample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static drillbit.protobuf.SamplePb.Sample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static drillbit.protobuf.SamplePb.Sample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.SamplePb.Sample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.SamplePb.Sample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.SamplePb.Sample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static drillbit.protobuf.SamplePb.Sample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static drillbit.protobuf.SamplePb.Sample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(drillbit.protobuf.SamplePb.Sample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code drillbit.protobuf.Sample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:drillbit.protobuf.Sample)
        drillbit.protobuf.SamplePb.SampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return drillbit.protobuf.SamplePb.internal_static_drillbit_protobuf_Sample_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return drillbit.protobuf.SamplePb.internal_static_drillbit_protobuf_Sample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                drillbit.protobuf.SamplePb.Sample.class, drillbit.protobuf.SamplePb.Sample.Builder.class);
      }

      // Construct using drillbit.protobuf.SamplePb.Sample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        target_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return drillbit.protobuf.SamplePb.internal_static_drillbit_protobuf_Sample_descriptor;
      }

      @java.lang.Override
      public drillbit.protobuf.SamplePb.Sample getDefaultInstanceForType() {
        return drillbit.protobuf.SamplePb.Sample.getDefaultInstance();
      }

      @java.lang.Override
      public drillbit.protobuf.SamplePb.Sample build() {
        drillbit.protobuf.SamplePb.Sample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public drillbit.protobuf.SamplePb.Sample buildPartial() {
        drillbit.protobuf.SamplePb.Sample result = new drillbit.protobuf.SamplePb.Sample(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          feature_ = feature_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.feature_ = feature_;
        result.target_ = target_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof drillbit.protobuf.SamplePb.Sample) {
          return mergeFrom((drillbit.protobuf.SamplePb.Sample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(drillbit.protobuf.SamplePb.Sample other) {
        if (other == drillbit.protobuf.SamplePb.Sample.getDefaultInstance()) return this;
        if (!other.feature_.isEmpty()) {
          if (feature_.isEmpty()) {
            feature_ = other.feature_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFeatureIsMutable();
            feature_.addAll(other.feature_);
          }
          onChanged();
        }
        if (!other.getTarget().isEmpty()) {
          target_ = other.target_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        drillbit.protobuf.SamplePb.Sample parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (drillbit.protobuf.SamplePb.Sample) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFeatureIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          feature_ = new com.google.protobuf.LazyStringArrayList(feature_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string feature = 1;</code>
       * @return A list containing the feature.
       */
      public com.google.protobuf.ProtocolStringList
          getFeatureList() {
        return feature_.getUnmodifiableView();
      }
      /**
       * <code>repeated string feature = 1;</code>
       * @return The count of feature.
       */
      public int getFeatureCount() {
        return feature_.size();
      }
      /**
       * <code>repeated string feature = 1;</code>
       * @param index The index of the element to return.
       * @return The feature at the given index.
       */
      public java.lang.String getFeature(int index) {
        return feature_.get(index);
      }
      /**
       * <code>repeated string feature = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the feature at the given index.
       */
      public com.google.protobuf.ByteString
          getFeatureBytes(int index) {
        return feature_.getByteString(index);
      }
      /**
       * <code>repeated string feature = 1;</code>
       * @param index The index to set the value at.
       * @param value The feature to set.
       * @return This builder for chaining.
       */
      public Builder setFeature(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFeatureIsMutable();
        feature_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string feature = 1;</code>
       * @param value The feature to add.
       * @return This builder for chaining.
       */
      public Builder addFeature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFeatureIsMutable();
        feature_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string feature = 1;</code>
       * @param values The feature to add.
       * @return This builder for chaining.
       */
      public Builder addAllFeature(
          java.lang.Iterable<java.lang.String> values) {
        ensureFeatureIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, feature_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string feature = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFeature() {
        feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string feature = 1;</code>
       * @param value The bytes of the feature to add.
       * @return This builder for chaining.
       */
      public Builder addFeatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFeatureIsMutable();
        feature_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object target_ = "";
      /**
       * <code>string target = 2;</code>
       * @return The target.
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          target_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string target = 2;</code>
       * @return The bytes for target.
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string target = 2;</code>
       * @param value The target to set.
       * @return This builder for chaining.
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string target = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTarget() {
        
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <code>string target = 2;</code>
       * @param value The bytes for target to set.
       * @return This builder for chaining.
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        target_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:drillbit.protobuf.Sample)
    }

    // @@protoc_insertion_point(class_scope:drillbit.protobuf.Sample)
    private static final drillbit.protobuf.SamplePb.Sample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new drillbit.protobuf.SamplePb.Sample();
    }

    public static drillbit.protobuf.SamplePb.Sample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sample>
        PARSER = new com.google.protobuf.AbstractParser<Sample>() {
      @java.lang.Override
      public Sample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Sample(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Sample> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sample> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public drillbit.protobuf.SamplePb.Sample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_drillbit_protobuf_Sample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_drillbit_protobuf_Sample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025proto/sample_pb.proto\022\021drillbit.protob" +
      "uf\")\n\006Sample\022\017\n\007feature\030\001 \003(\t\022\016\n\006target\030" +
      "\002 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_drillbit_protobuf_Sample_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_drillbit_protobuf_Sample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_drillbit_protobuf_Sample_descriptor,
        new java.lang.String[] { "Feature", "Target", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
